### ISSUE TITLE
Error from command

### ISSUE THREAD

**Issue by skdhanda** [cancerit/cgpBattenberg#109]
Please help me with the following error !!!

Errors from command: /opt/wtsi-cgp/bin/alleleCounter -l /var/spool/results/tmpBattenberg/1000genomesloci2012_chr9_split3366.txt -b /var/spool/data/Hu_333_normal.bam -o /var/spool/results/tmpBattenberg/Hu_333_normal_alleleFrequencies_chr9_split3366.txt -m 20 -r /var/spool/ref/genome.fa.fai -d

Output from command: /opt/wtsi-cgp/bin/alleleCounter -l /var/spool/results/tmpBattenberg/1000genomesloci2012_chr9_split3366.txt -b /var/spool/data/Hu_XXX_normal.bam -o /var/spool/results/tmpBattenberg/Hu_XXX_normal_alleleFrequencies_chr9_split3366.txt -m 20 -r /var/spool/ref/genome.fa.fai -d

Reading locis
Done reading locis
Multi pos start:
Use of uninitialized value $_ in concatenation (.) or string at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1690.

**Comment by drjsanger** [comment]
Hi @skdhanda could you let us know which version of cgpBattenberg  (or cgpBattenberg container ) you are using please?

**Comment by skdhanda** [comment]
Hi @drjsanger , 

I am using the following dockerfile to create a container, which downloaded this week only. I guess it should be the latest version. 


[Dockerfile_cgpbattenberg.txt](https://github.com/cancerit/cgpBattenberg/files/3875612/Dockerfile_cgpbattenberg.txt)

**Comment by drjsanger** [comment]
If you could run 
`docker run <YOUR IMAGE NAME> battenberg.pl -v` and tell use the output that would help us try to track this down.

**Comment by keiranmraine** [comment]
> Hi @drjsanger ,
> 
> I am using the following dockerfile to create a container, which downloaded this week only. I guess it should be the latest version.
> 
> [Dockerfile_cgpbattenberg.txt](https://github.com/cancerit/cgpBattenberg/files/3875612/Dockerfile_cgpbattenberg.txt)

Why are you building it? You can just pull it from quay.io linked from the container badge:

[![Quay Badge][quay-status]][quay-repo]

We don't tag a latest though (so it never changes unknowingly) so you need to specify which version:

`docker pull quay.io/wtsicgp/cgpbattenberg:3.5.2`


[quay-status]: https://quay.io/repository/wtsicgp/cgpbattenberg/status
[quay-repo]: https://quay.io/repository/wtsicgp/cgpbattenberg
[quay-builds]: https://quay.io/repository/wtsicgp/cgpbattenberg?tab=builds

**Comment by skdhanda** [comment]
Thanks @keiranmraine 

I could download and run the code with the above docker image (version 3.5.2).

The code is running for so long and here I am attaching log file and error file. It has the same error like before "Error from command". Please see my files attached. 


[Uploading out_log.txt…]()
[error.txt](https://github.com/cancerit/cgpBattenberg/files/3890482/error.txt)

Please help me with the error. 
Thanks,
Sandeep

**Comment by keiranmraine** [comment]
The original error you listed was:

```
Use of uninitialized value $_ in concatenation (.) or string at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1690.
```

This is not present in the file you've attached.

The repeated `Errors from command` and `Output from command` just signify the individual spawned processes and IF there is any output from STDERR/STDOUT it will appear between these sections so that you can tell which invocation raised the messages.

By the look of this you are not providing multiple CPUs via the `-threads` option, in this case it will take a very long time to process (resuming will be almost instant as it tracks where it is up to).

I'd make a guess that the reason the process failed this time is due to one of the following:

* Are you using an appropriately mapped input?
  * Expects GRCh37 mapped BAM files with no `chr` prefix.
* Does the host executing this have sufficient memory?
  * The R steps can require from ~30GB upwards.

**Comment by skdhanda** [comment]
Thanks @keiranmraine 
I have rerun the code with multiple threads and also increased the memory requested to 40GB. 

Though I have some questions related to <code>chr</code> prefix. 
Do I need to remove <code>chr</code> the mapped bam file?
My bam file looks like the following, as screenshot attached. 
![Screen Shot 2019-11-26 at 2 31 26 PM](https://user-images.githubusercontent.com/19757409/69678405-55c07a00-105a-11ea-8b7c-a2267614fedd.png)

There is also a <code>chr</code> prefix in 1000genomesloci2012_chr1*txt. 
Do I need to remove that too?

Please help. 

Thanks,
Sandeep

**Comment by keiranmraine** [comment]
Please see: https://github.com/cancerit/cgpBattenberg/wiki/Reference-name-conventions

This will only work for GRCh37 mapped input data, you should not need to modify the BAM file if the above is followed.

**Comment by skdhanda** [comment]
I am getting the following error while running it with GRCh38 and with 10 threads. 

```console
Automatically appending '.fai' to end of '-reference' option (see usage)
Thread 1 terminated abnormally: main=HASH(0x39f58a0) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread 2 terminated abnormally: main=HASH(0x4445cb0) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread 3 terminated abnormally: main=HASH(0x4d96290) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread 4 terminated abnormally: main=HASH(0x56e6870) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread 5 terminated abnormally: main=HASH(0x6036e50) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread 6 terminated abnormally: main=HASH(0x6987430) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread 7 terminated abnormally: main=HASH(0x72d7a10) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread 8 terminated abnormally: main=HASH(0x7c27ff0) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread 9 terminated abnormally: main=HASH(0x85785d0) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread 10 terminated abnormally: main=HASH(0x8ec8bb0) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 124.
Thread error: Can't open '/var/spool/results/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_allelecount.1.sh' for writing: 'No such file or directory' at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 262

Perl exited with active threads:
        0 running and unjoined
        9 finished and unjoined
        0 running and detached
```

Please also let me know, how much time it will take for a sample with 10 threads?

Thanks,
Sandeep

**Comment by keiranmraine** [comment]
Do you have sufficient space on the host disk?  Sounds like the disk is either full or you don't have write permissions... or if the container is working in /tmp on the host it's getting data reaped as it fills /tmp

**Comment by skdhanda** [comment]
Yes, I am running it on the cluster which has enough space in the hard disk and do have the write permissions.  To my best knowledge, it is not using the /tmp folder.
