### ISSUE TITLE
How was probloci.txt.gz generated?

### ISSUE THREAD

**Issue by zhouyangyu** [cancerit/cgpBattenberg#112]
Good day,

Our team at [Papaemmanuil lab](https://github.com/papaemmelab) @ MSKCC is developing an experimental tumor-only CNV caller, and we have seen the caller's performance increased significantly when we exclude SNPs at those positions: https://github.com/cancerit/cgpBattenberg/blob/1.4.0/perl/share/battenberg/probloci.txt.gz

Could you tell us how the file was generated?

Thanks,

Joe
Bioinformatics Engineer

**Comment by keiranmraine** [comment]
I have transferred this issue to cgpBattenberg as this is the more appropriate location for this (as that is where this reference file is used).

The probloci file is a manually curated set of SNPs that lie in noisy, and over represented segments of the genome.  @davidwedge @sdentro (and possibly @drjsanger) will have more detail.

**Comment by davidwedge** [comment]
Problem loci are identified as those that have allele frequencies outside the expected range in a substantial proportion of normal samples. These loci are likely also to report incorrect allele frequencies in some tumour samples.
Some definitions:
expected range = between 0.3 and 0.7 or greater than 0.9 or less than 0.1.
substantial proportion = 5%, but you should assess the optimal threshold for your sample set.

We also identified problematic *regions* by segmenting the proportion of problematic samples across all loci with PCF. Problematic regions were then identified as those with an average percentage of problematic samples greater than 4%, but again you should assess the optimal threshold with your samples.

**Comment by zhouyangyu** [comment]
Thank you for your explanation!
