### ISSUE TITLE
Inconsistency between BattenbergProfile*.png and battenberg_cn.vcf

### ISSUE THREAD

**Issue by yasunorikogure** [cancerit/cgpBattenberg#120]
Hi, there,

In my recent analysis, inconsistency between BattenbergProfile*.png and battenberg_cn.vcf was observed.

This is a cropped image from `TUMOR_BattenbergProfile_subclones.png`.

![image](https://user-images.githubusercontent.com/40516603/95084400-ca734300-0758-11eb-8ee7-d76c6ac07bbb.png)

And chr19 segmented data from` TUMOR_battenberg_cn.vcf` is like below:
```
19	226775	.	G	<CNV>	.	.	SVTYPE=CNV;END=29000203	GT:TCN:MCN:FCF:TCS:MCS:FCS	./.:2:1:.:.:.:.	./.:2:1:1:.:.:.
19	29000419	.	A	<CNV>	.	.	SVTYPE=CNV;END=40888806	GT:TCN:MCN:FCF:TCS:MCS:FCS	./.:2:1:.:.:.:.	./.:1:0:0.137879741027722:1:1:0.862120258972278
19	40889210	.	T	<CNV>	.	.	SVTYPE=CNV;END=42158202	GT:TCN:MCN:FCF:TCS:MCS:FCS	./.:2:1:.:.:.:.	./.:1:0:1:.:.:.
19	42161442	.	T	<CNV>	.	.	SVTYPE=CNV;END=59075531	GT:TCN:MCN:FCF:TCS:MCS:FCS	./.:2:1:.:.:.:.	./.:1:0:0.138225467424774:1:1:0.861774532575226
```
From the png file, apparently there is a focal deletion in the q arm of chr19, but no focal deletions seem to be called in the .vcf file.

I am using `dockstore-cgpwgs-2.0.1.simg` version through Singularity.
Could you help me figure out why this is happening and how I can fix it?

Thank you for your help!

**Comment by rulixxx** [comment]
Hi Yasunori,

I'm not all that familiar with the subclone plots... but I can see a thin like that would correspond with the long deletion you see in the vcf. Probably best to ask some of the more experienced users.

In case you'd like to try it out I just put in a new release with latest version of the Battenberg R code
(singularity pull docker://quay.io/wtsicgp/cgpbattenberg:3.7.0 )

Regards

Raul
________________________________

**Comment by yasunorikogure** [comment]
Hi Raul,

Yes, as you said, there is a think deletion, but VCF says that no focal deletion (but only long TCN=1 loss), and also minor CN in the minor clone is not zero, which is inconsistent...

And thanks for introducing your docker image. Does this include an allele count program, or should I do by myself?

**Comment by davidwedge** [comment]
I'm not very familiar with the vcf format, as this is produced by the cgpwrapper around Battenberg rather than the core code, but I believe the focal deletion *is* included in the vcf output, with a clonal deletion at 40-42MB and further subclonal deletions in the adjacent segments. The standard output from the core Battenberg code is a subclones.txt file, which you may find easier to interpret.

**Comment by yasunorikogure** [comment]
Thanks for your comment, David.
Region 19:40889210-42158202 seems to correspond to the focal deletion, with Total CN=1 (.:_1_:0:1:.:.:.). But around this region, total CN is also 1 _in VCF,_ which is so strange compaired to the plot (around this thin focal deletion, TCN seems 2 _in the plot_).

Perhaps I have to try the core Battenberg library without wrapper to see this problem will still exist.

**Comment by davidwedge** [comment]
I don't think there is a mismatch between the vcf file and the figure. The regions adjacent to this region are subclonal mixtures of TCN 2 and 1, so orange lines are shown at *both* copy number states.

**Comment by yasunorikogure** [comment]
Thanks for your comment, David. I found subclones.txt is truly consistent with the plot, so the plots seemed to be based on subclones.txt but not vcf file. In fact, I wasn't good because I was looking only at the VCF file and not at the subclones.txt carefully.

**Comment by yasunorikogure** [comment]
I'd like to report a small bug below related somewhat to battenberg_cn.vcf.
https://github.com/cancerit/cgpBattenberg/blob/ca97ccfd5cbddf1a7826e3d80e14c442bc5b6c46/perl/bin/battenberg_CN_to_VCF.pl#L125

In this "if" block, you would like to calculate TCN and MCN of the 2nd state.
