### ISSUE TITLE
problem with container: there is no package called ‘Battenberg’

### ISSUE THREAD

**Issue by GodloveD** [cancerit/cgpBattenberg#124]
Hi there,

I used the [Dockerfile](https://github.com/cancerit/cgpBattenberg/blob/dev/Dockerfile) to build [this container](https://hub.docker.com/r/godlovedc/cgpbattenberg).  I'm trying to run a command similar to this:

```
battenberg.pl -outdir outdir \
    -r hg38_ref/hg38.fa.fai \
    -tb bam_hg38/my_T.bam \
    -nb bam_hg38/my_N.bam \
    -ge XY \
    -impute-info impute_info.txt \
    -thousand-genomes-loc 1000genomesloci \
    -ignore-contigs-file GRCh38.exclude.contigs.txt \
    -gc-correction-loc battenberg_wgs_gc_correction_1000g_v3 \
    -species Human \
    -assembly 38 \
    -t 4
```
(Note that I've anonymized file and directory names in this and the following.) It chugs along merrily for a little while, but after a few minutes it yields this message:
```
General output can be found in this file: outdir/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_runbaflog.0.out
Errors can be found in this file: outdir/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_runbaflog.0.err

Wrapper script message:
"/usr/bin/time bash outdir/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_runbaflog.0.sh 1> outdir/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_runbaflog.0.out 2> outdir/tmpBattenberg/logs/Sanger_CGP_Battenberg_Implement_battenberg_runbaflog.0.err" unexpectedly returned exit value 1 at (eval 37) line 12.
 at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 235
```
Peeking in the `.err` file shows the following:
```
+ cd outdir/tmpBattenberg
+ /usr/bin/Rscript -e 'library(Battenberg);  getBAFsAndLogRs(tumourAlleleCountsFile.prefix="my_T_alleleFrequencies_chr", normalAlleleCountsFile.prefix="my_N_alleleFrequencies_chr", figuresFile.prefix="my_T_", BAFnormalFile="my_T_normalBAF.tab", BAFmutantFile="my_T_mutantBAF.tab", logRnormalFile="my_T_normalLogR.tab", logRmutantFile="my_T_mutantLogR.tab", combinedAlleleCountsFile="my_T_alleleCounts.tab", chr_names=as.vector(c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","X")), g1000file.prefix="/fdb/cancerit-wgs/cgpBattenberg/1000genomesloci/1000genomesAlleles2012_chr", minCounts=10, samplename="my_T", seed=1488823153) '
Error in library(Battenberg) : there is no package called ‘Battenberg’
Execution halted
Command exited with non-zero status 1
0.07user 0.14system 0:00.21elapsed 99%CPU (0avgtext+0avgdata 27060maxresident)k
12914inputs+8outputs (28major+10197minor)pagefaults 0swaps
```
Seems like the meat of the error is **`Error in library(Battenberg) : there is no package called ‘Battenberg’`**.  

So.  The Dockerfile installs R in the container.  Did it miss installing the Battenberg library?  Should I install that library within the container?  Or is there something pathological about the command that is causing this error?  

Any advice would be appreciated.  Thank you!

**Comment by keiranmraine** [comment]
Prebuilt containers are available on quay.io (see "container: ready" badge in [README](https://github.com/cancerit/cgpBattenberg/blob/dev/README.md)):

```
docker pull quay.io/wtsicgp/cgpbattenberg:3.7.1
```

Our internal CI shows the 3.7.1 image to be functional (it pulls the image from quay.io to test it)

**Comment by GodloveD** [comment]
I see now.  Thanks for that.  One more thing.  Could you make the link to the quay.io containers more explicit please?  Maybe add it somewhere in the readme?  imho it is pretty hidden in that badge, and I had a hard time tracking these down yesterday since quay.io is basically unsearchable, (and the group name there is different from the group name here, etc.)  Thanks for the quick reply!
