### ISSUE TITLE
Iterations must be a positive integer

### ISSUE THREAD

**Issue by SooLee** [cancerit/cgpBattenberg#14]
Hi I'm getting the following error message:
"Iterations must be a positive integer: 0 at ./battenberg.pl line 98."

The following is my command (directories simplified):
./battenberg.pl -o ~/battenberg/results -r ~/GATK-bundle/2.8/b37 -tb ~/MM3_T.raw.st.dm.ra.rc.bam -nb ~/MM3_N.raw.st.dm.ra.rc.bam -s 0 -e ~/battenberg/resources/impute/impute_info.txt -u ~/battenberg/resources/1000genomesloci/ -c ../files/probloci.txt -ig ~/battenberg/resources/unused.chrlist.txt -t 1

Can you help me resolve this? Thank you.

**Comment by keiranmraine** [comment]
Hi,

Could you rerun with the following modifications:

1. '-r' should be the full path to the `genome.fa.fai` file not just a directory or file name stub.
2. removing '-s 0'.  This is a flag and doesn't require a value, just presence when the sample is male.

Please let me know how you get on.

Regards,
Keiran

**Comment by SooLee** [comment]
Thank you for your help. Now I don't get that error message any more.
