### ISSUE TITLE
incomplete run?

### ISSUE THREAD

**Issue by SooLee** [cancerit/cgpBattenberg#15]
Hi, I'm getting the following four text output files other than per-chromosome intermediate files.

normalBAF.tab
mutantBAF.tab
normalLogR.tab
mutantLogR.tab

Am I supposed to get another text output file? I'm asking this because I was going to run PhyloWGS using the output file of Battenberg, and the format that PhyloWGS takes is different from the above four files.

Actually the program had got terminated at RunBAFLogR.R ("unexpectedly returned exit value 1 at (eval 360) line 13.") and when I ran just that part manually, it ran successfully and produced the above four files. Maybe it was supposed to be followed by another set of commands? Can you help me find what other commands I should run manually to complete the run? (I'm hoping not to have to run the whole thing again because it took a few days...)

Thank you.

**Comment by sdentro** [comment]
Hi,

Yes, that's possible. Use the -p parameter to specify the next steps. 
The following steps are available, of which you've completed the first two:

-p
Only process this step then exit, optionally set -index. The order of 
steps is as follows:
     allelecount *
     baflog
     imputefromaf *
     impute *
     combineimpute *
     haplotypebafs *
     cleanuppostbaf *
     plothaplotypes *
     combinebafs
     segmentphased
     fitcn
     subclones
     finalise

'*' denotes that the step has parallel processing. You can determine the 
total number by executing the command as:

battenberg.pl ...... -p <PROCESS> -j

1 to this value can be used with '-i' on these processes. For all other 
steps please use '-i 1'.


Best wishes,
Stefan


On 12/06/2015 20:33, SooLee wrote:
>
> Hi, I'm getting the following four text output files other than 
> per-chromosome intermediate files.
>
> normalBAF.tab
> mutantBAF.tab
> normalLogR.tab
> mutantLogR.tab
>
> Am I supposed to get another text output file? I'm asking this because 
> I was going to run PhyloWGS using the output file of Battenberg, and 
> the format that PhyloWGS takes is different from the above four files.
>
> Actually the program had got terminated at RunBAFLogR.R ("unexpectedly 
> returned exit value 1 at (eval 360) line 13.") and when I ran just 
> that part manually, it ran successfully and produced the above four 
> files. Maybe it was supposed to be followed by another set of 
> commands? Can you help me find what other commands I should run 
> manually to complete the run? (I'm hoping not to have to run the whole 
> thing again because it took a few days...)
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cancerit/cgpBattenberg/issues/15>.
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by SooLee** [comment]
Hi Stefan,

Thank you for your prompt answer.
When I run Battenberg with the -p parameter, I get similar error messages ("unexpectedly returned exit value 1 at (eval 360) line 13") for the individual R commands, whereas the R command itself runs with no problem. My original command is the same as in issue #14 (after correction). 

./battenberg.pl -o ~/battenberg/results -r ~/GATK-bundle/2.8/b37//human_g1k_v37_decoy.fasta.fai -tb ~/MM3_T.raw.st.dm.ra.rc.bam -nb ~/MM3_N.raw.st.dm.ra.rc.bam -e ~/battenberg/resources/impute/impute_info.txt -u ~/battenberg/resources/1000genomesloci/ -c ../files/probloci.txt -ig ~/battenberg/resources/unused.chrlist.txt -t 1

It may be helpful if there is an option to print out the R commands instead of actually running them. (or could this be a bug that can easily be fixed?)

Thank you.

Best,
Soo

**Comment by keiranmraine** [comment]
You can find log files which contain the executed command for each step in the output folder.

ls -ltrh ~/battenberg/results/tmpBatteberg/logs/*.err | tail

Will give you the most recently modified error logs

**Comment by keiranmraine** [comment]
@SooLee, I'm assuming this is now okay to close but please re-open if you need further assistance.
