### ISSUE TITLE
Option '1k-genome-loci-file' chromosome 24?

### ISSUE THREAD

**Issue by hdng** [cancerit/cgpBattenberg#19]
Hi,

I encountered this error when running battenberg using the following command:

battenberg -threads 12 -platform ILLUMINA -reference ref.fa.fai -tumbam tumor.bam -normbam norm.bam -is-male -impute-info /data/shared/battenberg-data/data/impute/impute_info.txt -thousand-genomes-loc /data/battenberg-data/data/1000genomesloci/ -outdir output

Then I turned on this option: -ignore-contigs-file with the text file on chrs/contigs that are not X,Y or 1-23, and still got the same error.

Please help. Thanks.

==== ERROR ====
Thread 24 terminated abnormally: Option '1k-genome-loci-file' (/data/shared/battenberg-data/data/1000genomesloci/1000genomesloci2012_chr24.txt) should be an existing file.
Thread error: Option '1k-genome-loci-file' (/data/shared/battenberg-data/data/1000genomesloci/1000genomesloci2012_chr24.txt) should be an existing file.

Perl exited with active threads:
	7 running and unjoined
	0 finished and unjoined
	0 running and detached
===========

**Comment by sdentro** [comment]
Hi,

There are no reference files for the Y chromosome included as Battenberg does not work there. It needs a good number of germline heterozygous SNPs to estimate copy number.

Please add the Y chromosome to the ignore contigs file.

Best,
Stefan

**Comment by salpie** [comment]
Hey, 

What should the ignore contigs file look like as I am having the same problem? I tried using the chrY.fa file and a text file that just said "chrY". Neither work. 

Thanks

**Comment by hdng** [comment]
I put all other chr/contigs that are different from chr1-chr23.

**Comment by keiranmraine** [comment]
That is correct, although why do you have chr23 and not chrX

**Comment by hdng** [comment]
Ahh. Morning. Should be chr1-chrX :)

**Comment by salpie** [comment]
Do you have an example file I can see? It's not working!

**Comment by sdentro** [comment]
Please find ours attached.

On 23/09/2015 15:09, salpie wrote:
>
> Do you have an example file I can see? It's not working!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cancerit/cgpBattenberg/issues/19#issuecomment-142613003>.
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE. 
Y
MT
GL000207.1
GL000226.1
GL000229.1
GL000231.1
GL000210.1
GL000239.1
GL000235.1
GL000201.1
GL000247.1
GL000245.1
GL000197.1
GL000203.1
GL000246.1
GL000249.1
GL000196.1
GL000248.1
GL000244.1
GL000238.1
GL000202.1
GL000234.1
GL000232.1
GL000206.1
GL000240.1
GL000236.1
GL000241.1
GL000243.1
GL000242.1
GL000230.1
GL000237.1
GL000233.1
GL000204.1
GL000198.1
GL000208.1
GL000191.1
GL000227.1
GL000228.1
GL000214.1
GL000221.1
GL000209.1
GL000218.1
GL000220.1
GL000213.1
GL000211.1
GL000199.1
GL000217.1
GL000216.1
GL000215.1
GL000205.1
GL000219.1
GL000224.1
GL000223.1
GL000195.1
GL000212.1
GL000222.1
GL000200.1
GL000193.1
GL000194.1
GL000225.1
GL000192.1
NC_007605
hs37d5

**Comment by hdng** [comment]
Here is my list for both hg19 and Grch37. It depends on what chrs you have
in your bam file I think.


chrY
Y
chrM
chr1_gl000191_random
chr1_gl000192_random
chr4_gl000193_random
chr4_gl000194_random
chr7_gl000195_random
chr8_gl000196_random
chr8_gl000197_random
chr9_gl000198_random
chr9_gl000199_random
chr9_gl000200_random
chr9_gl000201_random
chr11_gl000202_random
chr17_gl000203_random
chr17_gl000204_random
chr17_gl000205_random
chr17_gl000206_random
chr18_gl000207_random
chr19_gl000208_random
chr19_gl000209_random
chr21_gl000210_random
chrUn_gl000211
chrUn_gl000212
chrUn_gl000213
chrUn_gl000214
chrUn_gl000215
chrUn_gl000216
chrUn_gl000217
chrUn_gl000218
chrUn_gl000219
chrUn_gl000220
chrUn_gl000221
chrUn_gl000222
chrUn_gl000223
chrUn_gl000224
chrUn_gl000225
chrUn_gl000226
chrUn_gl000227
chrUn_gl000228
chrUn_gl000229
chrUn_gl000230
chrUn_gl000231
chrUn_gl000232
chrUn_gl000233
chrUn_gl000234
chrUn_gl000235
chrUn_gl000236
chrUn_gl000237
chrUn_gl000238
chrUn_gl000239
chrUn_gl000240
chrUn_gl000241
chrUn_gl000242
chrUn_gl000243
chrUn_gl000244
chrUn_gl000245
chrUn_gl000246
chrUn_gl000247
chrUn_gl000248
chrUn_gl000249
MT
GL000191.1
GL000192.1
GL000193.1
GL000194.1
GL000195.1
GL000196.1
GL000197.1
GL000198.1
GL000199.1
GL000200.1
GL000201.1
GL000202.1
GL000203.1
GL000204.1
GL000205.1
GL000206.1
GL000207.1
GL000208.1
GL000209.1
GL000210.1
GL000211.1
GL000212.1
GL000213.1
GL000214.1
GL000215.1
GL000216.1
GL000217.1
GL000218.1
GL000219.1
GL000220.1
GL000221.1
GL000222.1
GL000223.1
GL000224.1
GL000225.1
GL000226.1
GL000227.1
GL000228.1
GL000229.1
GL000230.1
GL000231.1
GL000232.1
GL000233.1
GL000234.1
GL000235.1
GL000236.1
GL000237.1
GL000238.1
GL000239.1
GL000240.1
GL000241.1
GL000242.1
GL000243.1
GL000244.1
GL000245.1
GL000246.1
GL000247.1
GL000248.1
GL000249.1

**Comment by salpie** [comment]
thank you
