### ISSUE TITLE
Error: Failed to find Rscript in PATH or local bin folder

### ISSUE THREAD

**Issue by salpie** [cancerit/cgpBattenberg#20]
I am getting this error:

Failed to find Rscript in PATH or local bin folder at /apps/cgpBattenberg/1.3.3/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 945.

I added this to my PATH, which is where all the Rscripts I can find are located, but this error is still popping up. Could you possibly advise?

PATH=/apps/cgpBattenberg/1.3.3/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg:$PATH

**Comment by keiranmraine** [comment]
Hi,

The R and Rsccript binaries need to be installed on your system to use battenberg.  This needs to be completed via a package manager.  Please contact your systems administrator if you don't have the relevant access to do this.

Kind regards,
Keiran
