### ISSUE TITLE
Error in the "finalise" step

### ISSUE THREAD

**Issue by jungminchoi** [cancerit/cgpBattenberg#25]
The run output the error below in the last step (based on the log files, it think it is the last step). Can you kindly help me troubleshoot?
Thank you!

```
Errors from command: cd /ycga-ba/labs/lifton/jc2545/MEND118/cgpBattenberg/MEND118/tmpBattenberg; /home/jc2545/programs/R-3.2.2/bin/Rscript /home/bioinfo/software/cgpBattenberg/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg/PlotHaplotypedData.R /home/bioinfo/software/cgpBattenberg/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/impute/impute_info.txt 21 MEND118_1T_2_chr21_heterozygousMutBAFs_haplotyped.txt MEND118_1T_2

Can't unlink():  at /home/bioinfo/software/cgpBattenberg/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 634
```

and my initial command was

```
[jc2545@compute-11-8 cgpBattenberg]$ perl /home/bioinfo/software/cgpBattenberg/bin/battenberg.pl -o $PWD/MEND118 -r /home/jc2545/ref_data/h_sapiens/1000genomes/2.5/b37/human_g1k_v37_decoy.fasta.fai -tb /ycga-ba/labs/lifton/jc2545/MEND118/tumor/MEND118_1T_2/MEND118_1T_2.bam -nb /ycga-ba/labs/lifton/jc2545/MEND118/MEND118-1/MEND118-1.bam -e /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/impute/impute_info.txt -u /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/1000genomesloci/ -c /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/probloci.txt -ig /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/ignored_b37.txt -t 32
```

**Comment by sdentro** [comment]
I think BB has completed but has failed during it's cleanup step. 
Perhaps some files had already disappeared. You can check if the final 
step of the algorithm has been completed by checking the tmpBattenberg 
directory for a file ending with "_subclones.txt". If so, please use the 
files from the tmp directory as a quick work-around.


On 07/01/2016 19:34, jungminchoi wrote:
>
> The run output the error below in the last step (based on the log 
> files, it think it is the last step) Can you kindly help me troubleshoot?
> Thank you!
>
> |Errors from command: cd 
> /ycga-ba/labs/lifton/jc2545/MEND118/cgpBattenberg/MEND118/tmpBattenberg; 
> /home/jc2545/programs/R-322/bin/Rscript 
> /home/bioinfo/software/cgpBattenberg/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg/PlotHaplotypedDataR 
> /home/bioinfo/software/cgpBattenberg/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg 
> /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/impute/impute_infotxt 
> 21 MEND118_1T_2_chr21_heterozygousMutBAFs_haplotypedtxt MEND118_1T_2 
> Can't unlink(): at 
> /home/bioinfo/software/cgpBattenberg/lib/perl5/Sanger/CGP/Battenberg/Implementpm 
> line 634 |
>
> and my initial command was
>
> |[jc2545@compute-11-8 cgpBattenberg]$ perl 
> /home/bioinfo/software/cgpBattenberg/bin/battenbergpl -o $PWD/MEND118 
> -r 
> /home/jc2545/ref_data/h_sapiens/1000genomes/25/b37/human_g1k_v37_decoyfastafai 
> -tb 
> /ycga-ba/labs/lifton/jc2545/MEND118/tumor/MEND118_1T_2/MEND118_1T_2bam 
> -nb /ycga-ba/labs/lifton/jc2545/MEND118/MEND118-1/MEND118-1bam -e 
> /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/impute/impute_infotxt 
> -u 
> /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/1000genomesloci/ 
> -c 
> /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/problocitxt 
> -ig 
> /ycga-ba/home/jc2545/programs/cgpBattenberg-dev/resource/ignored_b37txt -t 
> 32 |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cancerit/cgpBattenberg/issues/25>.
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by komalsrathi** [comment]
Hello,

We are using cgpBattenberg v1.3.1 and I am facing exactly the same issue. This is my err file:

```
+ set -o pipefail
+ battenberg.pl -o /ifs/work/leukgen/local/opt/leukcgp/test/1240 -is-male -r /ifs/work/gabow/ref/gr37/gr37.fasta.fai -tb /ifs/work/leukgen/local/opt/leukcgp/test/1240/data/D1240.bam -nb /ifs/work/leukgen/local/opt/leukcgp/test/1240/data/N1240.bam -e /ifs/work/leukgen/ref/homo_sapiens/37/battenberg/impute/impute_info.txt -u /ifs/work/leukgen/ref/homo_sapiens/37/battenberg/1000genomesloci -c /ifs/work/leukgen/ref/homo_sapiens/37/battenberg/probloci.txt.gz -ig /ifs/work/leukgen/ref/homo_sapiens/37/battenberg/ignored-contigs.txt -rs Human -ra 37 -pr WGS -pl HiSeq -p finalise -i 1
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.allele_tar_gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.subclone.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.hetDataPngs.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.hetBAFTxt.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.other.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.rafseg.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.impute_input.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.impute_output.tar.gz.0 as previously successful
Can't unlink():  at /ifs/work/leukgen/opt/cgp/5.18.4/cgpBattenberg/1.3.1/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 593
```

Lines 588-596 in Implement.pm:
```
#Cleanup other impute files.
	if(PCAP::Threaded::success_exists(File::Spec->catdir($tmp, 'progress'), @{['cleanup_impute',0]}) == 0){
		for(my $i=1; $i<=$options->{'job_count'}; $i++){
			my $file = File::Spec->catfile($tmp,sprintf($IMPUTE_INPUT,$options->{'tumour_name'},$i));
			next if($options->{'is_male'} && $file =~ m/chr(X|23)/ && ! -e $file); #Skip if male and X results aren't present, this is allowed...
			unlink glob $file;
		}
		PCAP::Threaded::touch_success(File::Spec->catdir($tmp, 'progress'), @{['cleanup_impute',0]});
	}
```

I added a print function just before `unlink glob $file` and it says that it is trying to remove files of the following pattern:

```D1240_impute_input_chr1_*K.*```

But these files are already removed by step 7 of Battenberg which is: cleanuppostbaf. The log file says that cleanuppostbaf executes this command for each chromosome (I am just showing chr1):

```rm -f D1240_impute_input_chr1_*K.* D1240_impute_output_chr1.txt```

**Comment by jungminchoi** [comment]
OK, thanks for your response. Indeed I do see *subclones.txt in the tmp directory. I will use this file in the mean time.

**Comment by komalsrathi** [comment]
Hello,

We are using cgpBattenberg v1.3.1 and I am facing exactly the same issue. This is my err file:

```
+ set -o pipefail
+ battenberg.pl -o /ifs/work/leukgen/local/opt/leukcgp/test/1240 -is-male -r /ifs/work/gabow/ref/gr37/gr37.fasta.fai -tb /ifs/work/leukgen/local/opt/leukcgp/test/1240/data/D1240.bam -nb /ifs/work/leukgen/local/opt/leukcgp/test/1240/data/N1240.bam -e /ifs/work/leukgen/ref/homo_sapiens/37/battenberg/impute/impute_info.txt -u /ifs/work/leukgen/ref/homo_sapiens/37/battenberg/1000genomesloci -c /ifs/work/leukgen/ref/homo_sapiens/37/battenberg/probloci.txt.gz -ig /ifs/work/leukgen/ref/homo_sapiens/37/battenberg/ignored-contigs.txt -rs Human -ra 37 -pr WGS -pl HiSeq -p finalise -i 1
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.allele_tar_gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.subclone.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.hetDataPngs.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.hetBAFTxt.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.other.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.rafseg.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.impute_input.tar.gz.0 as previously successful
Skipping Sanger::CGP::Battenberg::Implement::battenberg_finalise.impute_output.tar.gz.0 as previously successful
Can't unlink():  at /ifs/work/leukgen/opt/cgp/5.18.4/cgpBattenberg/1.3.1/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 593
```

Lines 588-596 in Implement.pm:
```
#Cleanup other impute files.
	if(PCAP::Threaded::success_exists(File::Spec->catdir($tmp, 'progress'), @{['cleanup_impute',0]}) == 0){
		for(my $i=1; $i<=$options->{'job_count'}; $i++){
			my $file = File::Spec->catfile($tmp,sprintf($IMPUTE_INPUT,$options->{'tumour_name'},$i));
			next if($options->{'is_male'} && $file =~ m/chr(X|23)/ && ! -e $file); #Skip if male and X results aren't present, this is allowed...
			unlink glob $file; # line 593
		}
		PCAP::Threaded::touch_success(File::Spec->catdir($tmp, 'progress'), @{['cleanup_impute',0]});
	}
```

I added a print function to print `$file` just before `unlink glob $file` (which is line 593 where finalise is failing) and it says that it is trying to remove files of the following pattern:

`D1240_impute_input_chr1_*K.*`

But these files are already removed by step 7 of Battenberg which is: **cleanuppostbaf**. The log file says that cleanuppostbaf executes this command for each chromosome (I am just showing chr1):

```rm -f D1240_impute_input_chr1_*K.* D1240_impute_output_chr1.txt```

Why is the script (lines 588-596) trying to delete files that are already being cleaned up by cleanuppostbaf?

**Comment by sdentro** [comment]
Could you please retry with the latest dev build to see if this issue has been resolved? I'm afraid you'll need to rerun from **imputefromaf** onwards. 

Please note that if you have the alleleFrequencies files per chromosome (output from the **allelecount** step) you can tarball them and supply to Battenberg as option **-a**. That'll save a lot of time as allele counting will not be performed again.

**Comment by keiranmraine** [comment]
Resolved by #17

**Comment by komalsrathi** [comment]
I ran finalise with the latest version v1.4.0 and it is still giving me the same error:

`Can't unlink():  at /ifs/work/leukgen/opt/cgp/5.18.4/cgpBattenberg/1.4.0/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 634`

This is the Implement.pm file:
```
	#Cleanup other impute files.
	if(PCAP::Threaded::success_exists(File::Spec->catdir($tmp, 'progress'), @{['cleanup_impute',0]}) == 0){
		for(my $i=1; $i<=$options->{'job_count'}; $i++){
			my $file = File::Spec->catfile($tmp,sprintf($IMPUTE_INPUT,$options->{'tumour_name'},$i));
			next if($options->{'is_male'} && $file =~ m/chr(X|23)/ && ! -e $file); #Skip if male and X results aren't present, this is allowed...
			unlink glob $file; # line 634
		}
		PCAP::Threaded::touch_success(File::Spec->catdir($tmp, 'progress'), @{['cleanup_impute',0]});
	}
```

Commenting out these lines fixes the problem.

**Comment by keiranmraine** [comment]
As indicated by @sdentro you will need to use the dev version, not a release.  Use this link to pull the bleeding edge version:

https://github.com/cancerit/cgpBattenberg/archive/dev.zip

**Comment by jungminchoi** [comment]
I forgot to leave the feedback here. 
The cgpBattenberg ran successfully without outputting errors with the dev version.
Thank you all.

**Comment by komalsrathi** [comment]
Ok, it is not a major issue for us, so we will wait for the next release. Thanks!
