### ISSUE TITLE
Incorrect TCN value in Battenberg TumourName_battenberg_cn.vcf.gz

### ISSUE THREAD

**Issue by komalsrathi** [cancerit/cgpBattenberg#27]
Hello,

I am running cgpBattenberg v1.3.1 because the newer versions are incompatible with the Perl version that we are using - v5.18.4. So after finalise step, I have the following VCF file that has information about the copy number for normal and tumour:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NORMAL  TUMOUR
1       776545  .       A       <CNV>   .       .       SVTYPE=CNV;END=249214082        GT:TCN:MCN      ./.:2:1 ./.:2:2
2       11319   .       A       <CNV>   .       .       SVTYPE=CNV;END=242985695        GT:TCN:MCN      ./.:2:1 ./.:2:2
3       60595   .       C       <CNV>   .       .       SVTYPE=CNV;END=197784354        GT:TCN:MCN      ./.:2:1 ./.:2:0
4       109540  .       G       <CNV>   .       .       SVTYPE=CNV;END=190789536        GT:TCN:MCN      ./.:2:1 ./.:2:0
```

This is my TumorName_subclones_chr1.png:

![d1238_subclones_chr1](https://cloud.githubusercontent.com/assets/7000615/12684109/efb19982-c68a-11e5-96db-a53885266ee4.png)

As you can see, the copy numbers are `2+2`. So the TUMOUR field that determines `GT:TCN:MCN` should be `./.:4:2` and not `./.:2:2`. The TCN i.e. total copy number here is 4 and not 2. I checked other chromosomes and found the same issue.

Thanks!

**Comment by sdentro** [comment]
Hi, Thank you for reporting this issue. It has been fixed in the latest 
cgpVcf release (v1.3.1) to be found here:

https://github.com/cancerit/cgpVcf/releases


On 29/01/2016 18:21, Komal Rathi wrote:
>
> Hello,
>
> I am running cgpBattenberg v131 because the newer versions are 
> incompatible with the Perl version that we are using - v5184 So after 
> finalise step, I have the following VCF file that has information 
> about the copy number for normal and tumour:
>
> |#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT NORMAL TUMOUR 1 776545 A 
> <CNV> SVTYPE=CNV;END=249214082 GT:TCN:MCN /:2:1 /:2:2 2 11319 A <CNV> 
> SVTYPE=CNV;END=242985695 GT:TCN:MCN /:2:1 /:2:2 3 60595 C <CNV> 
> SVTYPE=CNV;END=197784354 GT:TCN:MCN /:2:1 /:2:0 4 109540 G <CNV> 
> SVTYPE=CNV;END=190789536 GT:TCN:MCN /:2:1 /:2:0 |
>
> This is my TumorName_subclones_chr1png:
>
> d1238_subclones_chr1 
> <https://camo.githubusercontent.com/886d25af3a1b2b18a4a629330b459c469cdeea43/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f373030303631352f31323638343130392f65666231393938322d633638612d313165352d393664622d613533383835323636656534706e67>
>
> As you can see, the copy numbers are 2+2 So the TUMOUR field that 
> determines GT:TCN:MCN should be /:4:2 and not /:2:2 The TCN ie total 
> copy number here is 4 and not 2 I checked other chromosomes and found 
> the same issue
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cancerit/cgpBattenberg/issues/27>.
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by keiranmraine** [comment]
@komalsrathi , can you please indicate what the problem with 5.18.4 was?

**Comment by komalsrathi** [comment]
@keiranmraine I couldn't remember which step it was failing at so I installed the following latest versions and testing it. Will let you know.

```
allelecount 2.1.1
pcap 1.11.0
cgpVcf 1.2.6
cgpBattenberg 1.4.0
```

**Comment by sdentro** [comment]
@komalsrathi <https://github.com/komalsrathi> You'll need cgpVcf 1.3.1 
in order for this error message to disappear. It somehow did not get 
marked as the Latest release on Github. Can be downloaded here:

https://github.com/cancerit/cgpVcf/releases/tag/v1.3.1


On 01/02/2016 17:27, Komal Rathi wrote:
>
> @keiranmraine <https://github.com/keiranmraine> I couldn't remember 
> which step it was failing at so I installed the following latest 
> versions and testing it. Will let you know.
>
> |allelecount 2.1.1 pcap 1.11.0 cgpVcf 1.2.6 cgpBattenberg 1.4.0 |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cancerit/cgpBattenberg/issues/27#issuecomment-178082531>.
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by komalsrathi** [comment]
I used the versions that I have mentioned above:

![d1240_subclones_chr6](https://cloud.githubusercontent.com/assets/7000615/12820632/ec8e4d52-cb2d-11e5-9d09-62d1248792fe.png)

bbg output:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NORMAL  TUMOUR
6       209158  .       T       <CNV>   .       .       SVTYPE=CNV;END=170898626        GT:TCN:MCN      ./.:2:1 ./.:2:2
```

Shouldn't it be ./.:4:2 in TUMOUR?

**Comment by komalsrathi** [comment]
@keiranmraine 

I could successfully install and run the latest versions. Sorry for the confusion. I don't really know what changed. But the problem with the finalise output persists. Also the problem with deleting files that were already deleted by `imputefromaf` still remains.

**Comment by keiranmraine** [comment]
See: https://github.com/cancerit/cgpBattenberg/issues/25#issuecomment-179915422
