### ISSUE TITLE
Issue with battenberg.pl

### ISSUE THREAD

**Issue by esantosh1** [cancerit/cgpBattenberg#28]
Hi Team,

I am using cgpBattenberg for my phyloWGS Analysis. I get an error with the perl script. Input parameters are given below:

battenberg.pl -o ~/Desktop/ -r ~/Desktop/hg19_UCSC_unmasked.fai -e ../../impute/impute_info.txt -u ../../1000genomesloci/ -ge XX -tb ~/Desktop/Tumorbatch1-Outputs-Outputs-out_SO.bam -nb ~/Desktop/Normalbatch1-Outputs-Outputs-out_SO.bam -ig ./contigs_ignore.txt

**I get this error message: **
Use of uninitialized value $sname in sprintf at /opt/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 177.

Could you please help?

Thanks

**Comment by keiranmraine** [comment]
Hi,

Please can you check that your BAM file has valid RG header lines including a SM field.  Please see section 1.3 of the [specification](https://samtools.github.io/hts-specs/SAMv1.pdf)

Regards,
Keiran

**Comment by keiranmraine** [comment]
We can fix this up to give an informative warning/message but need to update a dependancy in [PCAP-code](https://github.com/ICGC-TCGA-PanCancer/PCAP-core/issues/96)

And also add the additional param to:

https://github.com/cancerit/cgpBattenberg/blob/ef74823547a161aa3214e9b1fadb9d770e146b41/perl/lib/Sanger/CGP/Battenberg/Implement.pm#L146-L147

**Comment by esantosh1** [comment]
Hi,

Thank you for the response. I am currently running the battenberg.pl with BAM Files having Read Groups (RG).
__battenberg.pl -o ~/Desktop/ -r /nfshome/iomics/Genomes/hg19_UCSC_unmasked/hg19_UCSC_unmasked.fa.fai -e ../../impute/impute_info.txt -u ../../1000genomesloci/ -ge XX -tb ~/Desktop/Tumorbatch1-Outputs-Outputs-out_SO_RG.bam -nb ~/Desktop/Normalbatch1-Outputs-Outputs_out_SO_RG.bam -ig ./contigs_ignore.txt _

The run is initiated however, I am not really sure if this is an error : 

_Errors from command: /opt/bin/alleleCounter -l /home/santosh/Softwares/cgpBattenberg/perl/bin/../../1000genomesloci/1000genomesloci2012_chr1.txt -b /home/santosh/Desktop/Tumorbatch1-Outputs-Outputs_out_SO_RG.bam -o /home/santosh/Desktop/tmpBattenberg/K_15_065_alleleFrequencies_chr1.txt -m 20 -r /nfshome/iomics/Genomes/hg19_UCSC_unmasked/hg19_UCSC_unmasked.fa.fai
_

_Output from command: /opt/bin/alleleCounter -l /home/santosh/Softwares/cgpBattenberg/perl/bin/../../1000genomesloci/1000genomesloci2012_chr1.txt -b /home/santosh/Desktop/Tumorbatch1-Outputs-Outputs_out_SO_RG.bam -o /home/santosh/Desktop/tmpBattenberg/K_15_065_alleleFrequencies_chr1.txt -m 20 -r /nfshome/iomics/Genomes/hg19_UCSC_unmasked/hg19_UCSC_unmasked.fa.fai

This proceeds to other chromosomes and still running !

Thanks

**Comment by keiranmraine** [comment]
Hi,

The wrapper code writes the commands being run to the output and error logs so that you can identify issues of individual commands, this is normal behaviour.  Also some commands write progress info to stderr so you should need to worry unless the wrapper script fails.

Regards,

**Comment by keiranmraine** [comment]
Resolved by db177cc
