### ISSUE TITLE
Bug in battenberg.pl

### ISSUE THREAD

**Issue by esantosh1** [cancerit/cgpBattenberg#29]
Hi,

I am able to find another bug in the battenberg.pl script.

Errors from command: /opt/bin/tabix -p vcf /home//Desktop/tmpBattenberg/Tum_logR_Baf_segmented.vcf.gz

Output from command: /opt/bin/tabix -p vcf /home//Desktop/tmpBattenberg/Tum_logR_Baf_segmented.vcf.gz

Use of uninitialized value in concatenation (.) or string at /opt/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 773.

The tool tabix and the vcf file exists but fails with an error. Tried commenting the specific line in the code and process it but still fails.

Thanks

**Comment by esantosh1** [comment]
Hi,

Any resolutions team ??

Thanks

**Comment by drjsanger** [comment]
@esantosh1 Does your bam file not contain an assembly in the SQ lines? 
If not you can provide it at commandline via `-assembly`

**Comment by kathryn-beal** [comment]
Hi,
Sorry for such a delay in replying.
We have recently released a new version of cgpBattenberg (v3.2.0) which uses a newer version of the Battenberg R files (version 2.2.5). I would suggest trying this version and see you still have the same issue.
I'll close the ticket now but please re-open it if you still see this problem.
Regards
Kathryn
