### ISSUE TITLE
Support on hg38 or b38 

### ISSUE THREAD

**Issue by wjaratlerdsiri** [cancerit/cgpBattenberg#35]
Hello, 

Now I would like to use the program with BAM files mapped to hg38. However,  I think the 3 following datasets are comared with b37: 1. 1000Genomes data; 2. impute_info.txt; and 3. probloci.txt.gz.

Do you have any plans for hg38 support?
If I lift over the files downloaded using "download_generate_bberg_ref_files.pl" with default settings from b37 to hg38, will this work with battenberg.pl?

Thankyou,
James

**Comment by kathryn-beal** [comment]
Hi James,
Sorry for the long delay. We do expect to have support for hg38 eventually. You could try lifting over the files in the meantime. You could also try asking the battenberg authors [here](https://github.com/Wedge-Oxford/battenberg) as they provide links to the reference files.
Regards
Kathryn
