### ISSUE TITLE
battenberg --> SPRUCE

### ISSUE THREAD

**Issue by ramaniak** [cancerit/cgpBattenberg#39]
Hello,
This not really an issue, more of a request for some clarification. 
I am using battenberg to create the copy number inputs necessary for executing spruce (https://github.com/raphael-group/spruce). I was in discussion with the spruce developer and he suggested I get in touch with @sdentro regarding this clarification. 

One of the inputs to spruce requires copy number information the header format for which is below:

```
 chr     startpos        endpos  BAF     pval    LogR    ntot    nMaj1_A nMin1_A frac1_A nMaj2_A nMin2_A frac2_A SDfrac_A        SDfrac_A_BS     frac1_A_0.025   frac1_A_0.975   frac1_A_corrected_for_purity   frac2_A_corrected_for_purity

```

The subclones.txt output from running battenberg has pretty much the same format except for the following
1. I am missing the final 2 columns (the fraction purity corrected). Would I be right in presuming this is obtained by multiplying the frac1_A and Frac2_A values by the  sample cellularity  value generated by the software? 
2. In my output, I have all of the columns above (minus the purity corrected cols) plus an additional set of columns for B, C, D, E, F as below

```
chr     startpos        endpos  BAF     pval    LogR    ntot    nMaj1_A nMin1_A frac1_A nMaj2_A nMin2_A frac2_A SDfrac_A        SDfrac_A_BS     frac1_A_0.025   frac1_A_0.975   nMaj1_B nMin1_B frac1_B nMaj2_B nMin2_B frac2_B SDfrac_B        SDfrac_B_BS     frac1_B_0.025   frac1_B_0.975   nMaj1_C nMin1_C frac1_C nMaj2_C nMin2_C frac2_C SDfrac_C        SDfrac_C_BS     frac1_C_0.025   frac1_C_0.975   nMaj1_D nMin1_D frac1_D nMaj2_D nMin2_D frac2_D SDfrac_D        SDfrac_D_BS     frac1_D_0.025   frac1_D_0.975   nMaj1_E nMin1_E frac1_E nMaj2_E nMin2_E frac2_E SDfrac_E        SDfrac_E_BS     frac1_E_0.025   frac1_E_0.975   nMaj1_F nMin1_F frac1_F nMaj2_F nMin2_F frac2_F SDfrac_F        SDfrac_F_BS     frac1_F_0.025   frac1_F_0.975
```

Could you please clarify how I interpret what A,B,C,D,E, and F ? 

Thanks
Arun

**Comment by ramaniak** [comment]
Anyone?

**Comment by keiranmraine** [comment]
Please contact the owners of the R codebase at https://github.com/Wedge-Oxford/battenberg
