### ISSUE TITLE
Error related to the GetBAFLogR.R process

### ISSUE THREAD

**Issue by 377945330** [cancerit/cgpBattenberg#45]
Hi,

When I run the battenberg.pl I got an error like this : 

[1] "data dims:"
[1] 37889806        7
[1] 37889806        7
[1] "minCount=10"
Error in `row.names<-.data.frame`(`*tmp*`, value = value) :
  invalid 'row.names' length
Calls: getBAFsAndLogRs ... rownames<- -> row.names<- -> row.names<-.data.frame

My command line is : 

battenberg.pl -o /PROJECT/09_CNV_RESULT/NT2/ 
                      -r /PROJECT/09_CNV_RESULT/hg19.fa.fai
                      -tb /PROJECT/ 05_BAM/NT2.bam
                      -nb /PROJECT/ 05_BAM/NT2_B.bam
                      -ge XY
                      -e /PROJECT/09_CNV_RESULT/impute/impute_info.txt 
                      -u /PROJECT/09_CNV_RESULT/1000genomesloci
                      -ig /PROJECT/09_CNV_RESULT/ignore.txt
                      -pr WXS
And the ignore.txt contains "Y" and "M"

Could you give me some help to solve this problem? 

Thank you !

**Comment by kathryn-beal** [comment]
Hi,
Sorry for such a delay in replying. 
We have recently released a new version of cgpBattenberg (v3.2.0) which uses a newer version of the Battenberg R files (version 2.2.5). I would suggest trying this version and see you still have the same issue.
I'll close the ticket now but please re-open it if you still see this problem.
Regards
Kathryn
