### ISSUE TITLE
Getting Error for 'From location copy check' 

### ISSUE THREAD

**Issue by dtm2117** [cancerit/cgpBattenberg#49]
hello,

for some reason I am not generating (tumorname_copynumberprofile.png), and other files, so during the finalize step it cannot locate them in the tmp directory, and the process fails. 

the "second_copynumberprofile" and related files ARE generated, and there are no errors until the finalise step. 

Any  idea on why this is happening? I've run the process on hundreds of samples previous to this one and have never had any issue. 

Thanks

**Comment by kathryn-beal** [comment]
Hi,
This seems strange. However, we have recently released a new version of battenberg (v3.2.0). Could you please try this version and report if you see any problems? I'll close the ticket now but please reopen it if there are still issues with this.
Regards
Kathryn
