### ISSUE TITLE
impute2 invoked oom-killer

### ISSUE THREAD

**Issue by marcRDM** [cancerit/cgpBattenberg#53]
Hi,

I am currently using Battenberg 1.5.3. It looks like when threaded, the impute step is launching 23 separate impute2, all asking independently for a lot of memory, which makes the system kill processes (even with 60 GB of RAM). Even if the step still runs and provides a proper input for the rest of Battenberg, I think we might loose information during this process and have no control on what is happening.  I saw that impute2 has it's own parallelisation process which is probably making sure that the sum of the requested memory does not exceed the available RAM. Would you have a workaround to suggest?

I am actually having quite a hard time when running the steps with the -t parameter in general, is it something you observed using that version?

Thank you very much in advance for your feedback,

Sincerely yours,
Marc

**Comment by kathryn-beal** [comment]
Hi Marc,
How are you running the wrapper script? You can specify the number of threads to use with the -t option. Have you tried using something like “-t 6” which will only use 6 threads? Are you running all the processes automatically or are you specifying the “-process” option which will run each process individually? This will give you more control as to how many threads to run for each process, for example.
Regards
Kathryn

**Comment by marcRDM** [comment]
Hi Kathryn,

Thank you very much for your feedback. I am running each step separately, each time with "-t 23" for the threaded ones. This is because I noticed allelecount was not running properly with a different number of threads.

Also, when I try to run allelecount with the expected parameters : "[...] -tb tumour_bam_path -nb normal_bam_path [...]", allelecount is performed on the tumour bam file only. The current workaround I am using is to run the allelecount step 2 times : "[...] -tb tumour_bam_path -nb tumour_bam_path [...]" and then "[...] -tb normal_bam_path -nb normal_bam_path [...]".

This is probably highly sub-optimal... Do you have any idea what is happening..?

Concerning the impute step, I am currently attempting a new run with -t 3 for that step, I will keep you posted on the outcome ! Thank you very much for the suggestion !

Regards,
Marc

**Comment by keiranmraine** [comment]
Hi @marcRDM, the `-t` option is how many cpu's will be used in parallel.  The allelecount step should run with 1 --> 2*chromosomes.  It works down a list of commands to execute, tumour 1-23 followed by normal 1-23.  If `-t 5` 5 are processed in parallel (note if a job completes the space is backfilled so it's not in clean 5 command blocks)

Also `battenberg.pl ... -p allelecount -j` should print the total number of jobs to complete a step (not threads).

@kathryn-beal, could you confirm that `-p allelecount -t 20` runs all jobs without any intervention?

**Comment by kathryn-beal** [comment]
Hi Marc,
I ran the allelecount step with -t 10 and it worked as expected, ie it ran over both samples.
Which version of PCAP-core are you using?
Regards
Kathryn

**Comment by marcRDM** [comment]
Hi Keiran, Hi Kathryn,

Thank you very much for your suggestions. Lowering the number of threads for the impute step worked as a charm ! I still have the issue with the allelecount step though. It is not that much of an issue actually as I am not waiting for the normal allelecount to finish to launch the tumour count. I think I am not loosing too much computer resources compared to a proper run even if it is annoying to double that step...

I am using PCAP v3.5.0, what about you?

Thanks a million,
Marc
