### ISSUE TITLE
Reduce allecount runtime

### ISSUE THREAD

**Issue by marcRDM** [cancerit/cgpBattenberg#54]
Hi,

Do you have any recommendation to reduce the allecount step runtime? Replacing the loci files with shorter ones for instance, any recommendation of an alternative list of snps? If so, do you have any insight on how it influences the results/performance?

Thank you very much,
Marc

**Comment by kathryn-beal** [comment]
Hi Marc,
We did some work on reducing the allele count step runtime in the latest version of cgpBattenberg (3.0.2) by splitting up the loci files into smaller chunks and running more jobs in parallel. However, the battenberg R files (version 2.2.5) is not packaged in this release because we are waiting for a public release of these. You could try running just the allele counting steps of the new release (splitlocifiles, allele count and concatallelecount) if you are able to run many jobs in parallel.

Kathryn

**Comment by marcRDM** [comment]
Hi @kathryn-beal ,

Thank you very much for your answer !
I think it might help a little indeed to split the loci files in equal chunks. However, how I run it currently already uses 99% of a 16 cores instance for hours before being affected by the non-equal length of the loci files.
I was thinking maybe 37 million snp positions is not absolutely necessary as the phasing step eventually merges events together.
Have you tried to run it with shorter loci files? Less than 1 million positions for instance?

Thank you very much,
Marc

**Comment by kathryn-beal** [comment]
Hi Marc,
We have recently released a new version of battenberg (v3.2.0) and of alleleCounter (3.3.1) where speed issues have been addressed.
I'll close the ticket now but please reopen it if you still have issues.
Regards
Kathryn

**Comment by isidroc** [comment]
Hi Kathryn,
Could you please elaborate more on how the speed issues have been improved? Thanks!

**Comment by drjsanger** [comment]
Hi @isidroc Battenberg uses [alleleCount](https://github.com/cancerit/alleleCount) under the hood to generate the counts required by the Battenberg algorithm. Initially alleleCount performed a pileup at each position listed in the file independently. We have now added a 'dense' mode to alleleCount. Using dense mode causes alleleCount to run pileup on a contig by contig basis and storing only the positions we require. This proved to be far faster than using a separate bam access for each position where positions in the file given to alleleCounter are closely packed. 

I hope that explains it

**Comment by isidroc** [comment]
Thanks for the clarification!
