### ISSUE TITLE
Error message in allelecounter

### ISSUE THREAD

**Issue by lennartkester** [cancerit/cgpBattenberg#56]
Hi All,

I'm trying to use Battenberg to do CNV calling on tumor samples. When I run it I get an error message in allelecounter.

Command:
battenberg.pl -o /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg -r /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/Homo_sapiens.GRCh37.GATK.illumina.fasta.fai -nb /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/P11NBULK_dedup.realigned.bam -tb /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/APKS1p17_dedup.realigned.bam -e /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg/impute/impute_info.txt -t 8  -u /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg2/1000genomesloci -ge XX -ig ignore_contig.txt

Error message:
Thread 2 terminated abnormally: "/gnu/store/9ycafnp3jz7fwa8d68ii8ff5khgq554n-profile/bin/alleleCounter -l /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg/1000genomesloci/1000genomesloci2012_chr1.txt -b /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/APKS1p17_dedup.realigned.bam -o /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg/tmpBattenberg/APKS1p17_alleleFrequencies_chr1.txt -m 20 -r /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/Homo_sapiens.GRCh37.GATK.illumina.fasta.fai" unexpectedly returned exit value 2 at /gnu/profiles/per-program/battenberg/lib/perl5/site_perl/5.24.0/Capture/Tiny.pm line 382 thread 2.

When I run allelecounter on its own I get a slightly more informative error message stating that it cannot open the .fai file. 

Command:
/gnu/store/9ycafnp3jz7fwa8d68ii8ff5khgq554n-profile/bin/alleleCounter -l /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg2/1000genomesloci/1000genomesloci2012_chr1.txt -b /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/APKS1p17_dedup.realigned.bam -o /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg2/tmpBattenberg/APKS1p17_alleleFrequencies_chr1.txt -m 20 -r /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/Homo_sapiens.GRCh37.GATK.illumina.fasta.fai

Error message:
[fai_load] build FASTA index.
[fai_build_core] different line length in sequence '(null)'.
/hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/Homo_sapiens.GRCh37.GATK.illumina.fasta.fai open: No such file or directory at /gnu/profiles/per-program/battenberg/lib/perl5/site_perl/5.24.0/Sanger/CGP/AlleleCount/Genotype.pm line 97.

The help of allelecounter states that is requires a .fasta file as input, but it is now given a .fai file. 
Could this be the issue, and do you have any idea on how to solve this issue?

Thanks a lot!

Lennart

**Comment by kathryn-beal** [comment]
Hi Lennart,
Could you tell me the battenberg version and alleleCounter version you are using by running the following commands:

battenberg_version.pl
/gnu/store/9ycafnp3jz7fwa8d68ii8ff5khgq554n-profile/bin/alleleCounter -v

Regards
Kathryn

**Comment by lennartkester** [comment]
Dear Kathryn,

Thanks a lot for your quick reply.

Battenberg is version 1.5.0
Allelecounter is version 3.0.1

Lennart

**Comment by kathryn-beal** [comment]
Dear Lennart,
I think there is some confusion about the version of alleleCounter being used. There are currently 2 versions, one written in c (bin/alleleCounter) and one is written in perl (bin/alleleCounter.pl). Battenberg runs the c version. Additionally, the reference option for the c version requires the fasta.fai file whilst the perl version requires the fasta file. If you ran the perl version (alleleCounter.pl) with the c version arguments then you would get the error message you saw when the code tries to index the index file. Could you try running the c version of the code and see what error you get?

/gnu/store/9ycafnp3jz7fwa8d68ii8ff5khgq554n-profile/bin/alleleCounter -l /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg2/1000genomesloci/1000genomesloci2012_chr1.txt -b /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/APKS1p17_dedup.realigned.bam -o /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg2/tmpBattenberg/APKS1p17_alleleFrequencies_chr1.txt -m 20 -r /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/Homo_sapiens.GRCh37.GATK.illumina.fasta.fai

Regards,
Kathryn

**Comment by lennartkester** [comment]
Dear Kathryn,

I tried to run the command as stated in your message, but I get the same error message.

command:
lkester@hpcs03 battenberg [env]$ /gnu/store/9ycafnp3jz7fwa8d68ii8ff5khgq554n-profile/bin/alleleCounter -l /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg2/1000genomesloci/1000genomesloci2012_chr1.txt -b /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/APKS1p17_dedup.realigned.bam -o /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/battenberg2/tmpBattenberg/APKS1p17_alleleFrequencies_chr1.txt -m 20 -r /hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/Homo_sapiens.GRCh37.GATK.illumina.fasta.fai


error message:
[fai_load] build FASTA index.
[fai_build_core] different line length in sequence '(null)'.
/hpc/hub_oudenaarden/lennart/viral_lineage/organoids/wgs/Homo_sapiens.GRCh37.GATK.illumina.fasta.fai open: No such file or directory at /gnu/profiles/per-program/battenberg-6-link/lib/perl5/site_perl/5.24.0/Sanger/CGP/AlleleCount/Genotype.pm line 97.

I figured out a workaround by running allelecount manually for all chromosomes with the fasta file as reference. But it would be great if I could run it without having to do this.

Thanks for your help!

Lennart

**Comment by kathryn-beal** [comment]
Dear Lennart,
I would like to check whether your copy of alleleCounter is the c or the perl version. The name implies the c version but your error implies the perl version. 
Could you try running the unix "file" command:

file /gnu/store/9ycafnp3jz7fwa8d68ii8ff5khgq554n-profile/bin/alleleCounter 

If it is perl, it should produce something like:
"a /software/perl-5.16.3/bin/perl script, ASCII text executable"
If it is c, something more like:
"ELF 64-bit LSB executable, x86-64, version 1 (SYSV) ..."

Could you also run the command with the -h (help option) and post the results? The help message is slightly different between the 2 versions so again it should be easy to see:

/gnu/store/9ycafnp3jz7fwa8d68ii8ff5khgq554n-profile/bin/alleleCounter -h

Regards,
Kathryn

**Comment by lennartkester** [comment]
Hi Kathryn,

You're right, /gnu/store/9ycafnp3jz7fwa8d68ii8ff5khgq554n-profile/bin/alleleCounter somehow has become a symbolic link to the allelecounter.pl script. So in fact it was running the allelecounter.pl script, explaining the error message.

Do you have any idea how to solve this? Or is this something for our systems administrator?

Thanks again!

Lennart

**Comment by kathryn-beal** [comment]
Hi Lennart,
You will need to download and install alleleCounter again as the c version will have been overwritten by the symbolic link. You will need to install it in a different place if someone needs the perl version to be called alleleCounter.

Regards,
Kathryn

**Comment by lennartkester** [comment]
Hi Kathryn,

Thanks a lot for your help. I'll contact the system administrator and see
what he can do.
For now it works with the workaround.

Best,

Lennart

2017-07-19 15:57 GMT+02:00 kathryn-beal <notifications@github.com>:

**Comment by kathryn-beal** [comment]
Hi Lennart,
Great. I'll close the ticket now.
Kathryn
