### ISSUE TITLE
Clarify that 1.5.3 is the only working version at this time

### ISSUE THREAD

**Issue by simozacca** [cancerit/cgpBattenberg#62]
Dear authors,

Could you please make more clear with a banner in the instructions that at the moment the only working version is the one including the R packages, as the ones up to 1.5.x? (Is this statement correct, right?)
Unfortunately, I was not able to understand from the message in the instructions that the R packages are still not available and, therefore, all the versions of Battenberg as the ones with 3.x.x are not currently working. I spent some time to figure out if I missed some steps (when trying to install the library in Rsupport there is an unbounded variable `BATTENBERG_PACKAGE`) and I hope that a clearer banner with that information may help other people that could be confused as I was.

Moreover, please add all the perl core modules in the prerequisites to install before running `./setup.sh`, since some systems (e.g. Red Hat systems) they may not have them available by default.

Thank you very much for your support,
Best,

Simone

**Comment by simozacca** [comment]
Other questions for whose more information may be very useful to add in the documentation:

1. What is the format of the `contigs_ignore` file? Is it simply a list where each line contains the name of a contig to ignore, right? Could you please add this information into the documentation?

2. The contigs to ignore are the one present either in the bam inputs or in the reference? I imagine they are the contigs present in the BAM, right?

3. Is it required that the chromosomes have the same format between the two bam inputs and between the BAM and the reference? In particular, they ll must be in the `chr` format or in the one without?

Thank you,

Simone

**Comment by simozacca** [comment]
Another note: I was trying to run Battenberg asking to ignore chromosomes X/Y by adding these to the `contigs_ignore.txt` file. However, these resulted in errors in the step `BafLog` where the execution halted because the allele count for chromosome 23 (corresponding to X/Y) was missing.

So, all the chromosomes 1-23 need to go through the execution, right?

**Comment by kathryn-beal** [comment]
Hi Simone,
I have just released a new version of cgpBattenberg (3.2.0) which now will install the Battenberg R files (v2.2.5) automatically.
I'll look at improving the documentation with your other suggestions.
Kathryn

**Comment by simozacca** [comment]
Dear author,

I installed the new version and indeed it installed correctly this time. I will start to play with this.

Best

**Comment by kathryn-beal** [comment]
Hi,
I've made another minor release with a bit more documentation. I've also updated the README.md and added an example ignore-contigs file to the wiki.
I'll close this ticket now. 
Kathryn
