### ISSUE TITLE
BUG in imputefrommaf - NAs introduce by coercion

### ISSUE THREAD

**Issue by simozacca** [cancerit/cgpBattenberg#63]
Dear authors,

I am trying to run the following simple battenberg run (Battenberg version 2.0.0 whereas all the other dependencies are at the last version):

`battenberg.pl -o out/ -r /n/fs/ragr-data/datasets/hg19/hg19_no_chr.fa.fai -tb /n/fs/ragr-data/datasets/Lote_CRC_2017/colon.bam -nb /n/fs/ragr-data/datasets/Lote_CRC_2017/blood.bam -ge XY -e /n/fs/ragr-code/bio/cgp/data/impute/impute_info.txt -u /n/fs/ragr-code/bio/cgp/data/1000genomesloci/ -ig ignore.txt -t 24`

Everything ran smoothly until the `imputefrommaf` step, where the execution got halted. In the error logs I found first a warning about the insertion of NAs by coercion and subsequently the next command failed (throwing the halt) because the file NA does not exists. Here below the details of the logs:

```
+ cd /opt/ragr/zaccaria/battenberg-run/102017/out/tmpBattenberg
+ /usr/bin/Rscript /n/fs/ragr-code/bio/cgp/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg/GenerateImputeInputFromAlleleFrequencies.R /n/fs/ragr-code/bio/cgp/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg /n/fs/ragr-code/bio/cgp/data/impute/impute_info.txt TRUE colon_alleleFrequencies.txt blood_alleleFrequencies.txt colon_impute_input_chr 22 /n/fs/ragr-code/bio/cgp/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg//probloci.txt.gz

+ cd /opt/ragr/zaccaria/battenberg-run/102017/out/tmpBattenberg
+ /usr/bin/Rscript /n/fs/ragr-code/bio/cgp/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg/GenerateImputeInputFromAlleleFrequencies.R /n/fs/ragr-code/bio/cgp/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg /n/fs/ragr-code/bio/cgp/data/impute/impute_info.txt TRUE colon_alleleFrequencies.txt blood_alleleFrequencies.txt colon_impute_input_chr 23 /n/fs/ragr-code/bio/cgp/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg//probloci.txt.gz
Warning message:
NAs introduced by coercion 
21.55user 0.43system 0:21.98elapsed 99%CPU (0avgtext+0avgdata 490792maxresident)k
0inputs+1648outputs (0major+212438minor)pagefaults 0swaps

+ cd /opt/ragr/zaccaria/battenberg-run/102017/out/tmpBattenberg
+ /usr/bin/Rscript /n/fs/ragr-code/bio/cgp/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg/GenerateImputeInputFromAlleleFrequencies.R /n/fs/ragr-code/bio/cgp/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg /n/fs/ragr-code/bio/cgp/data/impute/impute_info.txt TRUE colon_alleleFrequencies.txt blood_alleleFrequencies.txt colon_impute_input_chr 24 /n/fs/ragr-code/bio/cgp/lib/perl5/auto/share/module/Sanger-CGP-Battenberg-Implement/battenberg//probloci.txt.gz
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") : cannot open file 'NA': No such file or directory
Execution halted
```

I would really need to be able to run your tool, could you please help me to solve these issues?
Thank you very much,

Simone

**Comment by simozacca** [comment]
I also tried to reinstall the version 1.5.3 of Battenberg, but it crashed during the alleleCounter step. More specifically, this was my command 

```
battenberg.pl -o ./ -r /n/fs/ragr-data/datasets/hg19/hg19_no_chr.fa.fai -tb /n/fs/ragr-data/datasets/Lote_CRC_2017/colon.bam -nb /n/fs/ragr-data/datasets/Lote_CRC_2017/blood.bam -ge XY -e /n/fs/ragr-code/bio/cgp/data/impute/impute_info.txt -u /n/fs/ragr-code/bio/cgp/data/1000genomesloci/ -ig ignore.txt -t 50
```

The tool launches `alleleCounter` for all the chromosomes of the tumor sample and then it stops without launching the same allele counting on the normal sample. No errors are reported and in the folder `logs` there is not file *.err reporting any error or warning.

**Comment by kathryn-beal** [comment]
Hi Simone,
Could you try using the latest release, v3.2.0? This has been recently released and should be fully functional. 
I'll close the ticket now but please open another ticket if you are still having problems.
Regards
Kathryn
