### ISSUE TITLE
Running without chromosomes X/Y

### ISSUE THREAD

**Issue by simozacca** [cancerit/cgpBattenberg#66]
Dear authors,

I have some BAM files with no reads sequenced from chromosomes X/Y. I would like to run Battenberg on these datasets, How could I do? I notices from previous comments that I cannot add chromosomes X and Y to the `ignore list` and the pipeline seems to crash whenever it does not find these.
Could you please help me running these with some workaround?

Thanks,
Simone

**Comment by kathryn-beal** [comment]
Hi Simone,
The ignore-contigs-file should contain Y, MT and non-core reference sequences. 
It should be possible to add X to this. Please let us know if there is a problem.
I have added an example ignore-contigs-file in the wiki page:
https://github.com/cancerit/cgpBattenberg/wiki/Reference-name-conventions#ignore_contigstxt
Regards
Kathryn

**Comment by kathryn-beal** [comment]
I'll close the ticket now but please let us know if you have any problems.
Kathryn
