### ISSUE TITLE
Missing GC correction files

### ISSUE THREAD

**Issue by simozacca** [cancerit/cgpBattenberg#67]
Dear authors,

The automatic program for downloading the required data (`impute` and `1000 genome`) does not download anything related to GC correction and the pipeline crashes because it does not find such files with the following error:

```
+ /usr/bin/Rscript -e 'library(Battenberg);  gc.correct.wgs(Tumour_LogR_file="None_mutantLogR.tab", outfile="None_mutantLogR_gcCorrected.tab", correlations_outfile="None_GCwindowCorrelations.txt", gc_content_file_prefix="/1000_genomes_GC_corr_chr_", chrom_names=as.vector(c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22"))) '
Error in file(file, "rt") : cannot open the connection
Calls: gc.correct.wgs -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/1000_genomes_GC_corr_chr_1.txt.gz': No such file or directory
Execution halted
215.29user 8.54system 3:51.63elapsed 96%CPU (0avgtext+0avgdata 4821376maxresident)k
2339976inputs+32outputs (0major+3285639minor)pagefaults 0swaps
```

**Comment by kathryn-beal** [comment]
Hi,
Thank you for highlighting this issue. I will improve the documentation. For now, you can download the files from the battenberg R developers site here: 
https://github.com/Wedge-Oxford/battenberg
under the Required Reference Files.
Regards
Kathryn

**Comment by kathryn-beal** [comment]
You will also need to specify the directory of the files using the command line option -gc </path/to/files>
Again, I'll improve the documentation here too.
Kathryn

**Comment by kathryn-beal** [comment]
I'll close the ticket now but let us know if you have any issues.
Kathryn
