### ISSUE TITLE
./setup.sh: line 88: -v: command not found

### ISSUE THREAD

**Issue by weiliuyuan** [cancerit/cgpBattenberg#72]
Hi, 
I've got the error when i was installing the battenberg. i have successfully installed dependencies (PCAP-core, allelecount and cgpVcf). However, when i run setup.sh in cgpBatternberg, i got this massage (shown below). is it something wrong with my cpanm? 
Many thanks! 
Vivi

============== System information ====
+ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
+ uname -a
Linux dell 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
+ sw_vers
./setup.sh: line 70: sw_vers: command not found
+ system_profiler
./setup.sh: line 71: system_profiler: command not found
+ grep MemTotal /proc/meminfo
MemTotal:       16303588 kB
+ set +x

Installing build prerequisite File::ShareDir...+ -v --mirror http://cpan.metacpan.org --notest -l /home/ke/Work/ICGC File::ShareDir
./setup.sh: line 88: -v: command not found

**Comment by keiranmraine** [comment]
cgpBattenberg expects to be able to find `cpanm` in the PATH as it would have been installed/used by other dependencies.  If you are installing cgpBattenberg to a different install location you need to extend your PATH to include it.

e.g.
```
export PATH=PCAP-core_inst/bin:$PATH
./setup.sh....
```

**Comment by weiliuyuan** [comment]
Hi Keiran, 
Thanks for the help! 
I have already set up the PATH when i finished the three dependencies. 
However, i've still got the same error here when i tried to install cgpBattenberg....
Vivi
