### ISSUE TITLE
Too Many Files in tmpBattenberg

### ISSUE THREAD

**Issue by haoziyeung** [cancerit/cgpBattenberg#73]
I'm using cgpBattenberg for Tumor/Normal pair samples,my command is
`/gpfs/users/yanghao/software/cgpBattenberg-bin/bin/battenberg.pl -o 17k1811-DFN-2-20171130-4-1600237WES -reference /gpfs/users/yanghao/database/ref/b37/human_g1k_v37_decoy.fasta -tumbam /gpfs/output/20180302_Somatic_Mutation_CT_Panel_Test/1600237_ZSP/17k1811-DFN-2-20171130-4-1600237WES/17k1811-DFN-2-20171130-4.T.merge.bam -normbam /gpfs/output/20180302_Somatic_Mutation_CT_Panel_Test/1600237_ZSP/17k1811-DFN-2-20171130-4-1600237WES/1600237WES.N.merge.bam -impute-info /gpfs/users/yanghao/database/bundle/cgpBattenberg/impute/impute_info.txt -thousand-genomes-loc /gpfs/users/yanghao/database/bundle/cgpBattenberg/1000genomesloci/ -ignore-contigs-file /gpfs/users/yanghao/database/bundle/cgpBattenberg/ignore_contigs.txt -gc-correction-loc /gpfs/users/yanghao/database/bundle/cgpBattenberg/battenberg_wgs_gc_correction_1000g_v3/ -gender XX -threads `nproc` -protocol WXS`

And i found the tmp dir tmpBattenberg have 37889859 files.almost use all of my inodes(df -i),
and have some error logs

Scalars leaked: -1
Scalars leaked: -1
Scalars leaked: -1
Scalars leaked: -1
Scalars leaked: -1
Scalars leaked: -1
Scalars leaked: -1
Scalars leaked: -1
Thread 4 terminated abnormally: Use of uninitialized value $file_index in sprintf at /gpfs/users/yanghao/software/cgpBattenberg-bin/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 351.
Thread error: Use of uninitialized value $file_index in sprintf at /gpfs/users/yanghao/software/cgpBattenberg-bin/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 351.

Perl exited with active threads:
        23 running and unjoined
        0 finished and unjoined
        0 running and detached

and my sample is target sequence(smaller than whole exome sequence),can anybody tell my how can i reduce the tmp files and what's wrong of my command?

and cgpBattenberg is so slow(even i use threads),and my perl is support thread.
Thanks all.

**Comment by keiranmraine** [comment]
cgpBattenberg is for WGS sequencing only, we will fix the `-protocol` arg to remove WXS and improve our documentation (#74).  We have no idea how you have managed to generate that many files. as we only hit ~8k in our pipeline which generates additional files.

Some other information if you do use for WGS data.

1. You can have the `tmpBattenberg/logs/*.out` and `tmpBattenberg/logs/*.err` delete automatically on successful completion by setting the following env variable:
`export PCAP_THREADED_REM_LOGS=1`
1. Are you using the current version of cgpBattenberg with an up to version of [alleleCount, v3.3.1](https://github.com/cancerit/alleleCount/releases) or greater
