### ISSUE TITLE
ERROR: Thread 72 terminated abnormally: main=HASH(0x293f568) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 157

### ISSUE THREAD

**Issue by leiendeckerlu** [cancerit/cgpBattenberg#82]
Hi there,

I was trying to run the battenberg.pl script that is part of the cgwgs container like this:

```
singularity exec ./dockstore-cgpwgs-2.0.0.simg battenberg.pl \
-outdir ./battenberg_1/ \
-reference /docker/ftp.sanger.ac.uk/pub/cancer/dockstore/human/core_ref_GRCh37d5/genome.fa \
-tumbam /docker/1T/1T.bam \
-normbam /docker/1N/1N.bam \
-gender XY \
-impute-info /docker/testa/impute/impute_info.txt \
-thousand-genomes-loc /docker/testa/1000genomesloci/ \
-ignore-contigs-file /docker/ignore_contigs_GRCh37d5.txt \
-gc-correction-loc /docker/battenberg/battenberg_wgs_gc_correction_1000g_v3 \
-threads 7 \
-protocol WGS \
-platform ILLUMINA \
-species Human
```

but (independent of the thread number) and the available RAM/CPU I get the following error always that the same step:

https://gist.github.com/leiendeckerlu/91278ad1e595b837788972c5d1401ea5

Any insides on what is going wrong here?

Thanks!

**Comment by leiendeckerlu** [comment]
Update: The error reported above can be solved by adding the Y chromosome to the list of ignored contigs.

Update 2: battenberg now fails at the following step:

> Thread 70 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 71 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 72 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 73 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 74 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 75 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 76 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 77 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 78 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 79 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 80 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 81 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 82 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread 83 terminated abnormally: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> Thread error: Failed to find impute2 in PATH or local bin folder at /opt/wtsi-cgp/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1543.
> 
> Perl exited with active threads:
> 	0 running and unjoined
> 	13 finished and unjoined
> 	0 running and detached

However, the impute2 exe is in the path and can also be called form inside the docker container - still it does not seem to be found...

Thank you!

**Comment by leiendeckerlu** [comment]
@keiranmraine any idea on this? still didn't get it running...
Thank you!

**Comment by keiranmraine** [comment]
Sorry for the delay, we've never used this container to actually run BB just the collection of the allele counts.  Clearly we need to determine what is missing and do an update.

**Comment by keiranmraine** [comment]
Moved to container repo as that is where the fix is required.
