### ISSUE TITLE
using hg19

### ISSUE THREAD

**Issue by thelingxichen** [cancerit/cgpBattenberg#86]
Hi,

I have done the alignment using hg19, how can I update the command options, "-assembly 19" ?

Thanks

**Comment by paprikachan** [comment]
and how can I update 1000genomesloci and impute files?

**Comment by kathryn-beal** [comment]
Hi,
The reference files were created by the battenberg developers so you can ask them via their github page: 
https://github.com/Wedge-Oxford/battenberg
Regards
Kathryn
