### ISSUE TITLE
FitCopyNumber.R?

### ISSUE THREAD

**Issue by jsmedmar** [cancerit/cgpBattenberg#88]
Last time I used cgpBattenberg was version 1.4.0 and we were using `FitCopyNumber.R` to fit a new profile. That script is not included anymore. Does this means that the profile reported by battenberg is now always the correct one? Or there is another approach to refitting?

**Comment by jsmedmar** [comment]
But do you pull the code at runtime? Or on setup.sh. I just installed battenberg on a container and could not find the files on a recursive search in the installation bundle..

**Comment by jsmedmar** [comment]
Ah I found the R installation helper, thanks

**Comment by kathryn-beal** [comment]
Thanks. I'll resolve the ticket now.
