### ISSUE TITLE
Error in base.gw.plot(bafsegmented, nAPlot, nBPlot, colourTotal, colourMinor, : argument "chrs" is missing, with no default

### ISSUE THREAD

**Issue by tamaraprieto** [cancerit/cgpBattenberg#89]
Hi,

I was running battenberg.pl like this:

`
battenberg.pl \
        -outdir ${WORKDIR}/BATTENBERG/ \
        -reference ${RESDIR}/${REF}.fa \
        -normbam ${WORKDIR}/${HEALTHY}.dedup.bam \
        -tumbam ${WORKDIR}/${SAMPLE}.dedup.bam \
        -gender XY \
        -impute-info data/impute/impute_info.txt \
        -thousand-genomes-loc data/1000genomesloci/ \
        -ignore-contigs-file ignore_contigs.txt \
        -gc-correction-loc battenberg_wgs_gc_correction_1000g_v3 \
        -prob-loci probloci_270415.txt
`

And I got the following error twice: 

Error in base.gw.plot(bafsegmented, nAPlot, nBPlot, colourTotal, colourMinor,  : 
  argument "chrs" is missing, with no default
Calls: fit.copy.number ... base.gw.plot -> text -> text.default -> as.graphicsAnnot
In addition: Warning message:
In log(d) : NaNs produced
Execution halted
"cd /mnt/lustre/scratch/home/uvi/be/tpf/CLL04/RESULTS/BATTENBERG/tmpBattenberg; /opt/cesga/easybuild-cesga/software/Compiler/gcc/6.4.0/R/3.5.0/bin/Rscript -e 'library(Battenberg);  fit.copy.number(samplename="CLL04.BM", outputfile.prefix="CLL04.BM_", inputfile.baf.segmented="CLL04.BM.BAFsegmented.txt", inputfile.baf="CLL04.BM_mutantBAF.tab", inputfile.logr="CLL04.BM_mutantLogR.tab", dist_choice=0, ascat_dist_choice=1, min.ploidy=1.6, max.ploidy=4.8, min.rho=0.1, max.rho=1, min.goodness=0.63, uninformative_BAF_threshold=0.51, gamma_param=1 ) '" unexpectedly returned exit value 1 at /opt/cesga/easybuild-cesga/software/Compiler/gcc/6.4.0/pcap-core/3.5.0/lib/perl5/PCAP/Threaded.pm line 215.
 at /opt/cesga/easybuild-cesga/software/Compiler/gcc/6.4.0/pcap-core/3.5.0/lib/perl5/PCAP/Threaded.pm line 212

Do you have an idea of what can be happening here?

Thanks in advance, 

Tamara

**Comment by sdentro** [comment]
Hello Tamara,

Could you please check whether there is any data in 
CLL04.BM.BAFsegmented.txt? The "chrs" variable is determined based on 
the first column of the BAFsegmented file. Is there data in the 
CLL04.BM_mutantLogR.tab and CLL04.BM_mutantBAF.tab files?

Best,

Stefan


On 26/10/2018 15:42, tamaraprieto wrote:
>
> Hi,
>
> I was running battenberg.pl like this:
>
> |battenberg.pl \ -outdir ${WORKDIR}/BATTENBERG/ \ -reference 
> ${RESDIR}/${REF}.fa \ -normbam ${WORKDIR}/${HEALTHY}.dedup.bam \ 
> -tumbam ${WORKDIR}/${SAMPLE}.dedup.bam \ -gender XY \ -impute-info 
> data/impute/impute_info.txt \ -thousand-genomes-loc 
> data/1000genomesloci/ \ -ignore-contigs-file ignore_contigs.txt \ 
> -gc-correction-loc battenberg_wgs_gc_correction_1000g_v3 \ -prob-loci 
> probloci_270415.txt|
>
> And I got the following error twice:
>
> Error in base.gw.plot(bafsegmented, nAPlot, nBPlot, colourTotal, 
> colourMinor, :
> argument "chrs" is missing, with no default
> Calls: fit.copy.number ... base.gw.plot -> text -> text.default -> 
> as.graphicsAnnot
> In addition: Warning message:
> In log(d) : NaNs produced
> Execution halted
> "cd 
> /mnt/lustre/scratch/home/uvi/be/tpf/CLL04/RESULTS/BATTENBERG/tmpBattenberg; 
> /opt/cesga/easybuild-cesga/software/Compiler/gcc/6.4.0/R/3.5.0/bin/Rscript 
> -e 'library(Battenberg); fit.copy.number(samplename="CLL04.BM", 
> outputfile.prefix="CLL04.BM_", 
> inputfile.baf.segmented="CLL04.BM.BAFsegmented.txt", 
> inputfile.baf="CLL04.BM_mutantBAF.tab", 
> inputfile.logr="CLL04.BM_mutantLogR.tab", dist_choice=0, 
> ascat_dist_choice=1, min.ploidy=1.6, max.ploidy=4.8, min.rho=0.1, 
> max.rho=1, min.goodness=0.63, uninformative_BAF_threshold=0.51, 
> gamma_param=1 ) '" unexpectedly returned exit value 1 at 
> /opt/cesga/easybuild-cesga/software/Compiler/gcc/6.4.0/pcap-core/3.5.0/lib/perl5/PCAP/Threaded.pm 
> line 215.
> at 
> /opt/cesga/easybuild-cesga/software/Compiler/gcc/6.4.0/pcap-core/3.5.0/lib/perl5/PCAP/Threaded.pm 
> line 212
>
> Do you have an idea of what can be happening here?
>
> Thanks in advance,
>
> Tamara
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_cgpBattenberg_issues_89&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=aJbv9w72SDCK2q1kk0vyRJCYJEQD2NyyofkgwN0RuJU&s=3BnIAzE1m0BOsvWTcBc7KzMroscQS_6OxcJ-Y2yggLs&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AD3tQII74kz02vAim4GW-2Dgqh9iA-2DgIP5ks5uox9agaJpZM4X8YHH&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=aJbv9w72SDCK2q1kk0vyRJCYJEQD2NyyofkgwN0RuJU&s=bvZtRNym9jYPqDmwdT30E79yZcFWdI4dpu6kk3KM-Yk&e=>.
>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by tamaraprieto** [comment]
Hi Stephan, 

Thanks for the answer. There is data in the three files for chromosome 1 to 22 and X.

[uvibetpf@fs6801 tmpBattenberg]$ head CLL04.BM.BAFsegmented.txt
Chromosome	Position	BAF	BAFphased	BAFseg
1	784903	0.727272727272727	0.727272727272727	0.507577425529399
1	811716	0.9	0.9	0.507577425529399
1	811735	0.9	0.9	0.507577425529399
1	811765	0.333333333333333	0.333333333333333	0.507577425529399
1	824398	0.444444444444444	0.444444444444444	0.507577425529399
1	828166	0.454545454545455	0.454545454545455	0.507577425529399
1	828883	0.48	0.48	0.507577425529399
1	830181	0.6875	0.6875	0.507577425529399
1	831909	0.6	0.6	0.507577425529399
[uvibetpf@fs6801 tmpBattenberg]$ head CLL04.BM_mutantLogR.tab
Chromosome	Position	CLL04.BM
1	10583	0.869503809445599
1	13302	0.169064091304507
1	13327	0.214151980833045
1	51476	0.197078467474104
1	51479	0.00443338953170801
1	51914	0.465113554366264
1	51954	0.324069672911081
1	52058	0.128422106807161
1	52144	0.284541308724443
[uvibetpf@fs6801 tmpBattenberg]$ head CLL04.BM_mutantBAF.tab
Chromosome	Position	CLL04.BM
1	10583	0.444444444444444
1	13302	1
1	13327	1
1	51476	1
1	51479	0.404761904761905
1	51914	0
1	51954	0
1	52058	0.914285714285714
1	52144	1
 
I can share with you any other info you need. 

Best, 

Tamara

**Comment by tamaraprieto** [comment]
Here you are the copynumberprofile figure. 

![cll04 bm_copynumberprofile](https://user-images.githubusercontent.com/7628968/47713210-9bc9c500-dc31-11e8-865f-d7f84f0e71a2.png)

Do you need something else?This is the list of the figures generated:

[uvibetpf@fs6801 tmpBattenberg]$ ls *png
CLL04.BM_chr10_heterozygousData.png  CLL04.BM_RAFseg_chr20.png
CLL04.BM_chr11_heterozygousData.png  CLL04.BM_RAFseg_chr21.png
CLL04.BM_chr12_heterozygousData.png  CLL04.BM_RAFseg_chr22.png
CLL04.BM_chr13_heterozygousData.png  CLL04.BM_RAFseg_chr2.png
CLL04.BM_chr14_heterozygousData.png  CLL04.BM_RAFseg_chr3.png
CLL04.BM_chr15_heterozygousData.png  CLL04.BM_RAFseg_chr4.png
CLL04.BM_chr16_heterozygousData.png  CLL04.BM_RAFseg_chr5.png
CLL04.BM_chr17_heterozygousData.png  CLL04.BM_RAFseg_chr6.png
CLL04.BM_chr18_heterozygousData.png  CLL04.BM_RAFseg_chr7.png
CLL04.BM_chr19_heterozygousData.png  CLL04.BM_RAFseg_chr8.png
CLL04.BM_chr1_heterozygousData.png   CLL04.BM_RAFseg_chr9.png
CLL04.BM_chr20_heterozygousData.png  CLL04.BM_RAFseg_chrX.png
CLL04.BM_chr21_heterozygousData.png  CLL04.BM_segment_chr10.png
CLL04.BM_chr22_heterozygousData.png  CLL04.BM_segment_chr11.png
CLL04.BM_chr23_heterozygousData.png  CLL04.BM_segment_chr12.png
CLL04.BM_chr2_heterozygousData.png   CLL04.BM_segment_chr13.png
CLL04.BM_chr3_heterozygousData.png   CLL04.BM_segment_chr14.png
CLL04.BM_chr4_heterozygousData.png   CLL04.BM_segment_chr15.png
CLL04.BM_chr5_heterozygousData.png   CLL04.BM_segment_chr16.png
CLL04.BM_chr6_heterozygousData.png   CLL04.BM_segment_chr17.png
CLL04.BM_chr7_heterozygousData.png   CLL04.BM_segment_chr18.png
CLL04.BM_chr8_heterozygousData.png   CLL04.BM_segment_chr19.png
CLL04.BM_chr9_heterozygousData.png   CLL04.BM_segment_chr1.png
CLL04.BM_copynumberprofile.png       CLL04.BM_segment_chr20.png
CLL04.BM_distance.png                CLL04.BM_segment_chr21.png
CLL04.BM.germline.png                CLL04.BM_segment_chr22.png
CLL04.BM_RAFseg_chr10.png            CLL04.BM_segment_chr2.png
CLL04.BM_RAFseg_chr11.png            CLL04.BM_segment_chr3.png
CLL04.BM_RAFseg_chr12.png            CLL04.BM_segment_chr4.png
CLL04.BM_RAFseg_chr13.png            CLL04.BM_segment_chr5.png
CLL04.BM_RAFseg_chr14.png            CLL04.BM_segment_chr6.png
CLL04.BM_RAFseg_chr15.png            CLL04.BM_segment_chr7.png
CLL04.BM_RAFseg_chr16.png            CLL04.BM_segment_chr8.png
CLL04.BM_RAFseg_chr17.png            CLL04.BM_segment_chr9.png
CLL04.BM_RAFseg_chr18.png            CLL04.BM_segment_chrX.png
CLL04.BM_RAFseg_chr19.png            CLL04.BM.tumour.png
CLL04.BM_RAFseg_chr1.png

Best, 

Tamara

**Comment by tamaraprieto** [comment]
I am using v. 3.3.0. I can run the analysis in another sample to check. 
Log file also has data for chromosomes 1 to 22 and X. 

[uvibetpf@fs6801 tmpBattenberg]$ head CLL04.BM.logRsegmented.txt
1	784903	-0.0683953475252653
1	824398	-0.0683953475252653
1	828166	-0.0683953475252653
1	828883	-0.0683953475252653
1	830181	-0.0683953475252653
1	831909	-0.0683953475252653
1	832066	-0.0683953475252653
1	832112	-0.0683953475252653
1	832178	-0.0683953475252653
1	832398	-0.0683953475252653

Best, 

Tamara

**Comment by sdentro** [comment]
Hmm... Which version of ASCAT is there installed, is it v2.5.1?

Best,

Stefan


On 30/10/2018 11:35, tamaraprieto wrote:
>
> I am using v. 3.3.0. I can run the analysis in another sample to check.
> Log file also has data for chromosomes 1 to 22 and X.
>
> [uvibetpf@fs6801 tmpBattenberg]$ head CLL04.BM.logRsegmented.txt
> 1 784903 -0.0683953475252653
> 1 824398 -0.0683953475252653
> 1 828166 -0.0683953475252653
> 1 828883 -0.0683953475252653
> 1 830181 -0.0683953475252653
> 1 831909 -0.0683953475252653
> 1 832066 -0.0683953475252653
> 1 832112 -0.0683953475252653
> 1 832178 -0.0683953475252653
> 1 832398 -0.0683953475252653
>
> Best,
>
> Tamara
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_cgpBattenberg_issues_89-23issuecomment-2D434266939&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=LXBeBUIZGlRztHJroK626sF2EtSXkJnKdR2ADIAEsFs&s=acHdHK940Oy00Nk94log2-FBcIE-4l5_C24ypOj-DeE&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AD3tQMZkY8kfG7E9p1u9aMhsv7GBoir9ks5uqDmSgaJpZM4X8YHH&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=LXBeBUIZGlRztHJroK626sF2EtSXkJnKdR2ADIAEsFs&s=nzmPn5yas6uGOksDxtIle7k5K5-5IxA6sKAlKRc9Gm0&e=>.
>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by tamaraprieto** [comment]
Yes, ASCAT_2.5. Should I update it?
 
Best,

Tamara

**Comment by sdentro** [comment]
Yes please! v2.5.1 and v2.5.2 should work, but 2.5.1 is recommended as 
it is tied to cgpBatttenberg 3.3.0.

This is one of the differences between ASCAT v2.5 and v2.5.1:

-    ascat.plotNonRounded(ploidy_opt1, rho_opt1, goodnessOfFit_opt1, 
nonaberrant, nAfull, nBfull, y_limit, bafsegmented, ch,lrr)
+   ascat.plotNonRounded(ploidy_opt1, rho_opt1, goodnessOfFit_opt1, 
nonaberrant, nAfull, nBfull, y_limit, bafsegmented, ch,lrr, chrnames)

That would explain the error message!

Best wishes,

Stefan


On 30/10/2018 12:22, tamaraprieto wrote:
>
> Yes, ASCAT_2.5. Should I update it?
>
> Best,
>
> Tamara
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_cgpBattenberg_issues_89-23issuecomment-2D434279376&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=TVs3y69mxXd7AE8MrTncu1bqcBgLdP4m5UmFMqrdzT0&s=Tf6sualbfcUCUi-cmoKk3sfHDKulam_ngpYhioZgjkA&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AD3tQHtuo3355nVR7DAW2UvQd01vkjBUks5uqESdgaJpZM4X8YHH&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=TVs3y69mxXd7AE8MrTncu1bqcBgLdP4m5UmFMqrdzT0&s=nspZVml9nbsj7cC-1N-M7pk6ulSA8q0en7RuDyLeRpk&e=>.
>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by tamaraprieto** [comment]
Thank you very much and sorry for not having thought about ascat version. 

Best, 

Tamara

**Comment by sdentro** [comment]
No worries! This version should not have been allowed by the Battenberg R package. Just pushed a fix that will go into the next version. Thanks for reporting!
Best,
Stefan

**Comment by tamaraprieto** [comment]
Hi again, 

This time I ran the program using the Ascat version 2.5.1 and I am still getting exactly the same error. Do you have any other idea?

Best, 

Tamara

**Comment by tamaraprieto** [comment]
Hi Stefan

It is not me who installs the software in the cluster so I cannot be completely sure but when I load the modules and enter R, I get the following R package versions:

Battenberg_2.2.6
ASCAT_2.5.1

Do you think the pipeline can still be running another Ascat version?

Best,

Tamara

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

Matrix products: default
BLAS/LAPACK: /mnt/netapp1/Optcesga_FT2/opt/cesga/easybuild-cesga/software/Core/imkl/2018.2.199/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
[1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C
[3] LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8
[5] LC_MONETARY=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8
[7] LC_PAPER=en_US.UTF-8 LC_NAME=C
[9] LC_ADDRESS=C LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] Battenberg_2.2.6 readr_1.1.1 ggplot2_2.2.1 ASCAT_2.5.1
[5] RColorBrewer_1.1-2

loaded via a namespace (and not attached):
[1] Rcpp_0.12.17 grid_3.5.0 plyr_1.8.4 R6_2.2.2
[5] gtable_0.2.0 scales_0.5.0 pillar_1.2.3 rlang_0.2.1
[9] lazyeval_0.2.1 tools_3.5.0 munsell_0.4.3 hms_0.4.2
[13] compiler_3.5.0 pkgconfig_2.0.1 colorspace_1.3-2 tibble_1.4.2

**Comment by sdentro** [comment]
Hi Tamara,

Well, we've checked that there is data and the list of chromosome names 
is determined based on that, so that seems to check out. cgpBattenberg 
v3.3.0 comes with Battenberg v2.2.8 and ASCAT v2.5.1, so I'm not sure 
how you've ended up with both R packages being different. Perhaps it's 
best to upgrade to the Battenberg v2.2.8 R package and further chase up 
to make sure your pipeline loads the correct packages.

Best,

Stefan


On 05/11/2018 09:50, tamaraprieto wrote:
> Hi Stefan
>
> It is not me who installs the software in the cluster so I cannot be 
> completely sure but when I load the modules and enter R, I get the 
> following R package versions:
>
> Battenberg_2.2.6
> ASCAT_2.5.1
>
> Do you think the pipeline can still be running another Ascat version?
>
> Best,
>
> Tamara
>
> > sessionInfo()
> R version 3.5.0 (2018-04-23)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)
>
> Matrix products: default
> BLAS/LAPACK: 
> /mnt/netapp1/Optcesga_FT2/opt/cesga/easybuild-cesga/software/Core/imkl/2018.2.199/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so
>
> locale:
> [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C
> [3] LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8
> [5] LC_MONETARY=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8
> [7] LC_PAPER=en_US.UTF-8 LC_NAME=C
> [9] LC_ADDRESS=C LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
>
> attached base packages:
> [1] stats graphics grDevices utils datasets methods base
>
> other attached packages:
> [1] Battenberg_2.2.6 readr_1.1.1 ggplot2_2.2.1 ASCAT_2.5.1
> [5] RColorBrewer_1.1-2
>
> loaded via a namespace (and not attached):
> [1] Rcpp_0.12.17 grid_3.5.0 plyr_1.8.4 R6_2.2.2
> [5] gtable_0.2.0 scales_0.5.0 pillar_1.2.3 rlang_0.2.1
> [9] lazyeval_0.2.1 tools_3.5.0 munsell_0.4.3 hms_0.4.2
> [13] compiler_3.5.0 pkgconfig_2.0.1 colorspace_1.3-2 tibble_1.4.2
>
>
>
> On 5 Nov 2018, 10:42 +0100, Stefan Dentro <notifications@github.com>, 
> wrote:
> > Hi Tamara,
> >
> > Which version of the Battenberg R package are you using? Are you
> > confident ASCAT 2.5.1 is actually loaded by the pipeline?
> >
> > Best wishes,
> >
> > Stefan
> >
> >
> > On 01/11/2018 17:13, tamaraprieto wrote:
> > >
> > > Hi again,
> > >
> > > This time I ran the program using the Ascat version 2.5.1 and I am
> > > still getting exactly the same error. Do you have any other idea?
> > >
> > > Best,
> > >
> > > Tamara
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub
> > > 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_cgpBattenberg_issues_89-23issuecomment-2D435110132&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=ooMPvk0suSfPWZOL7ObKpUwH8MSvwek8xRsi-mEUfhU&s=AlLTAV728PwAc0jnDWyXvGrtLl6nhQOK6oeCw-H84D8&e=>,
> > > or mute the thread
> > > 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AD3tQEPfEaY1jc6lzcMoThPSUQC428wTks5uqyuhgaJpZM4X8YHH&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=ooMPvk0suSfPWZOL7ObKpUwH8MSvwek8xRsi-mEUfhU&s=MjRrf8Wm1rBTDuqONKGov8-q3Slj6rBNgHgx2EMdGG0&e=>.
> > >
> >
> >
> >
> >
> > --
> > The Wellcome Sanger Institute is operated by Genome Research
> > Limited, a charity registered in England with number 1021457 and a
> > company registered in England with number 2742969, whose registered
> > office is 215 Euston Road, London, NW1 2BE.
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub, or mute the thread.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_cgpBattenberg_issues_89-23issuecomment-2D435815328&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=Yr7jIMJthfHuAC4DR-cifySfBIlmhbbNsFF9hBZZjB0&s=1ePzg01_zNdV57gk-HNJY6OjZmsdrkP0SR9mCeslJgo&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AD3tQGLSKXxpURIvCMwbGlwgh48n305jks5usAnxgaJpZM4X8YHH&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=Yr7jIMJthfHuAC4DR-cifySfBIlmhbbNsFF9hBZZjB0&s=y2SWBrH3qD3Ah5BABBpSrFT0iQbXwmwObeFKR7bOjNQ&e=>.
>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by tamaraprieto** [comment]
Hi Stefan, 

I ran the program again this time using R Battenberg package version v.2.2.8. Now the error is different: 

Use of uninitialized value in concatenation (.) or string at /opt/cesga/easybuild-cesga/software/Compiler/gcc/6.4.0/cgpbattenberg/3.3.0-R-3.5.1/lib/perl5/Sanger/CGP/Battenberg/Implement.pm line 1281.

Do you have an idea of what can be happening now?Many of the files have been created. 

Best, 

Tamara

**Comment by kathryn-beal** [comment]
Hi Tamara,
Could you try specifying the species and reference assembly using the -rs and -ra flags?
eg battenberg.pl ... -rs Human -ra GRCh37d5
Regards
Kathryn

**Comment by tamaraprieto** [comment]
Hi Kathryn, 

I specified it and now it works. Thank you both very much. 

Best, 

Tamara
