### ISSUE TITLE
The number of loci files error (hg38)

### ISSUE THREAD

**Issue by Hansol-Park** [cancerit/cgpBattenberg#90]
Hi, I’m trying to run Battenberg for bam files aligned to hg38. I made required files such as 1000genome loci files, GC correction files, etc., as like hg19 version’s ones. But it gave me an error: **The number of loci files created 0 is not the same as the number requested 23.** I saw the question about a similar issue and then checked the number of rows in fa.fai and that of ignore_contigs file. They are 3,366 and 3,343, respectively, and the difference between them is 23. 

The command and files are as below:
**Shell file: prep_battenberg.sh**
#!/bin/bash
battenberg=/appl/battenberg/cgpBattenberg/bin/battenberg.pl
reference=/data/REFERENCE/hg38/Homo_sapiens_assembly38.fasta.fai
impute=ref/hg38/impute_hg38/impute_info_hg38.txt
snp_loci=ref/hg38/1000genomesloci_hg38/
ignore=ref/hg38/GRCh38.exclude.contigs.txt
gc=ref/hg38/gc_correction_1000g_hg38/
output_dir=./output_battenberg/
tumor_bam=$1
normal_bam=$2
gender=$3

mkdir -p $output_dir
$battenberg -o $output_dir -r $reference -tb $tumor_bam -nb $normal_bam -ge $gender -e $impute -u $snp_loci -ig $ignore -gc $gc -t 4 -ra 38

**Running command**
sh prep_battenberg.sh /data/Processed/Batch1/Tumor/PM-AU-0010-T-A1_merged_piped_hg38.sortfix_mrkdup.BQSR.bam /data/Processed/Batch1/Normal/PM-AU-0010-N-A1_merged_piped_hg38.sortfix_mrkdup.BQSR.bam XY

**hg38.fa.fai ----------------------------------------------------------------------------------------**
chr1    248956422       112     100     101
chr2    242193529       251446211       100     101
chr3    198295559       496061788       100     101
chr4    190214555       696340415       100     101
chr5    181538259       888457250       100     101
chr6    170805979       1071811004      100     101
chr7    159345973       1244325155      100     101
chr8    145138636       1405264700      100     101
chr9    138394717       1551854835      100     101
chr10   133797422       1691633613      100     101
chr11   135086622       1826769123      100     101
chr12   133275309       1963206725      100     101
chr13   114364328       2097814901      100     101
chr14   107043718       2213322999      100     101
chr15   101991189       2321437268      100     101
chr16   90338345        2424448481      100     101
chr17   83257441        2515690322      100     101
chr18   80373285        2599780450      100     101
chr19   58617616        2680957593      100     101
chr20   64444167        2740161498      100     101
chr21   46709983        2805250232      100     101
chr22   50818468        2852427440      100     101
chrX    156040895       2903754205      100     101
chrY    57227415        3061355656      100     101
chrM    16569   3119155468      100     101
chr1_KI270706v1_random  175055  3119172340      100     101
chr1_KI270707v1_random  32032   3119349282      100     101
chr1_KI270708v1_random  127682  3119381772      100     101
chr1_KI270709v1_random  66860   3119510867      100     101
chr1_KI270710v1_random  40176   3119578532      100     101
chr1_KI270711v1_random  42210   3119619246      100     101
chr1_KI270712v1_random  176043  3119662016      100     101
…
**Ignore_contigs -------------------------------------------------------------------------------------**
chrY
chrM
chr1_KI270706v1_random
chr1_KI270707v1_random
chr1_KI270708v1_random
chr1_KI270709v1_random
chr1_KI270710v1_random
chr1_KI270711v1_random
chr1_KI270712v1_random
chr1_KI270713v1_random
chr1_KI270714v1_random
chr2_KI270715v1_random
chr2_KI270716v1_random
chr3_GL000221v1_random
chr4_GL000008v2_random
chr5_GL000208v1_random
chr9_KI270717v1_random
chr9_KI270718v1_random
chr9_KI270719v1_random
chr9_KI270720v1_random
chr11_KI270721v1_random
chr14_GL000009v2_random
chr14_GL000225v1_random
chr14_KI270722v1_random
chr14_GL000194v1_random
chr14_KI270723v1_random
chr14_KI270724v1_random
…

**Comment by kathryn-beal** [comment]
Hi,
The problem may be the naming of the files in your snp_loci directory, ie ref/hg38/1000genomesloci_hg38/
The code is expecting them to conform to the pattern "1000genomesloci2012_chr*.txt"  and "1000genomesAlleles2012_chr". This should be something to fix in the future but for now, you will need to make sure they follow this pattern.
Please let me know if this fixes the problem.
Kathryn

**Comment by Hansol-Park** [comment]
Hi, Kathryn.
Thank you for the answer. I corrected the name of 1000genome loci files as you mentioned and also rename GC correction files as "1000_genomes_GC_corr_chr_*.txt.gz". However, I got another error message as follows.
Skipping Sanger_CGP_Battenberg_Implement_battenberg_splitlocifiles.0 as previously successful
Thread 1 terminated abnormally: Found more than one file for index 1
Thread 2 terminated abnormally: Found more than one file for index 2
Thread 3 terminated abnormally: Found more than one file for index 3
Thread 4 terminated abnormally: Found more than one file for index 4
Thread error: Found more than one file for index 1

Perl exited with active threads:
        0 running and unjoined
        3 finished and unjoined
        0 running and detached

I think now the only difference between my hg38 files and your hg19 files is... hap, legend, and genetic map files of X chromosome (in the impute folder) are not divided into PAR1, PAR2, and nonPAR. (That's because snp loci in X chromosome were all located in the nonPAR region. I downloaded it at ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/) 
Is this made the above error?

**Comment by kathryn-beal** [comment]
Hi,
I suspect the problem are the splitloci files created in the tmpBattenberg directory. You probably have ones created by the previous run which are conflicting with the current run. Could you remove everything in the tmpBattenberg directory (including it's sub-directories) and try again? You should end up with 23 files in tmpBattenberg looking like: 1000genomesloci2012_chr[1-23]_split[1-23].txt ie one split file for each chromosome.
Kathryn

**Comment by Hansol-Park** [comment]
I solved the above error, thanks to your help! However, I faced other problem.... (sorry, it is hard for me to decode perl code.) 
- The last generated outputs in tmpBattenberg are BAF, LogR, and alleleCounts.tab files. These files only have column names. 
- In alleleFrequencies_chr* files, Count_A, C, G, T and Good_depth columns are all filled by zero.
- In progress folder, there are splitlocifiles, allelecount, and concat_allelecount files. 
- In logs folder, allelecount.*.err files look like, 
```
+ /appl/battenberg/cgpBattenberg/bin/alleleCounter -l /data/hspark/05_cnv_callers/battenberg/output_battenberg/tmpBattenberg/1000genomesloci2012_chr23_split1.txt -b /data/Processed/Batch1/Tumor/PM-AU-0010-T-A1_merged_piped_hg38.sortfix_mrkdup.BQSR.bam -o /data/hspark/05_cnv_callers/battenberg/output_battenberg/tmpBattenberg/PM-AU-0010-T-A1_alleleFrequencies_chr23_split1.txt -m 20 -r /data/REFERENCE/hg38/Homo_sapiens_assembly38.fasta.fai -d
Reading locis
Done reading locis
Multi pos start:
2.18user 1.45system 0:03.83elapsed 94%CPU (0avgtext+0avgdata 2927164maxresident)k
0inputs+57784outputs (0major+728809minor)pagefaults 0swaps
```
It reports "0inputs+57784outputs", while the same log file of other samples (done successfully; aligned to hg19) reports many inputs+0outputs (e.g., 6193448inputs+0outputs (0major+776171minor)pagefaults 0swaps).
-  runbaflog.0.err files in logs folder is finished with 
```
Parsed with column specification:
cols(
  position = col_integer(),
  a0 = col_integer(),
  a1 = col_integer()
)
```
which doesn't have comment like below (which is present in the successfully ran case).
```
688.13user 237.22system 16:12.44elapsed 95%CPU (0avgtext+0avgdata 10789804maxresident)k
4514376inputs+8outputs (147major+26809764minor)pagefaults 0swaps
```

I checked the format of 1000genomesAlleles2012_chr*.txt files I made are the same as those of hg19 version. 
Thanks again!

**Comment by kathryn-beal** [comment]
Hi,
We don't currently support GRCh38 so the help I can give is limited. You can try also asking the authors of the core battenberg code here: [https://github.com/Wedge-Oxford/battenberg](url)
You could try running one of the allelecounter steps by hand to see if that gives you insight into what could be the problem (the values shouldn't be all 0). The command to run is  the one in the allelecount.*.err file.
Kathryn

**Comment by kathryn-beal** [comment]
Hi,
I'll resolve this ticket now.
Kathryn

**Comment by rdmorin** [comment]
Has anyone made GRCh38 reference files available?
