### ISSUE TITLE
This error when running the code

### ISSUE THREAD

**Issue by beginner984** [cancerit/cgpBattenberg#93]
Hi

I am permanently getting this error

`Errors from command: /opt/wtsi-cgp/bin/alleleCounter`

This is my code 

`singularity exec /local/containers/dockstore-cgpwgs-2.0.1.simg battenberg.pl -o /temp/hgig/fi1d18/ -tb /temp/hgig/fi1d18/Oesophageal/1631_WTSI-OESO_121_1pre/mapped_sample/HUMAN_1000Genomes_hs37d5_genomic_WTSI-OESO_121_1pre.dupmarked.bam -nb /temp/hgig/fi1d18/Oesophageal/1631_WTSI-OESO_005_b/mapped_sample/HUMAN_1000Genomes_hs37d5_genomic_WTSI-OESO_005_b.dupmarked.bam -r /temp/hgig/fi1d18/hs37d5.fa -ge L -u /home/fi1d18/battenberg_impute_v3/1000genomesloci -e /home/fi1d18/battenberg_impute_v3/impute/impute_info.txt -ig /temp/hgig/fi1d18/ignoreContig.txt -gc /home/fi1d18/battenberg_impute_v3/battenberg_wgs_gc_correction_1000g_v3/`

**Comment by keiranmraine** [comment]
Please provide the complete log output.  At first glance this looks like a header indicating that any error output from the spawned process will appear after this line.  These are generated even if no error output occurs as it is redirected to the file rather than held in memory.

**Comment by keiranmraine** [comment]
No response
