### ISSUE TITLE
[E::hts_idx_push] Unsorted positions on sequence #6: 135999720 followed by 1

### ISSUE THREAD

**Issue by TakaYamaguchi** [cancerit/cgpBattenberg#94]
Hi,

I'm testing the latest (3.3.0) cgpBattenberg and encountered the index error probably due to the use of mathematical notation (e+08) in VCF. Could you please look into it?

tabix -p vcf  sample_logR_Baf_segmented.vcf.gz

[E::hts_idx_push] Unsorted positions on sequence #6: 135999720 followed by 1

6       135996036       .       .       .       .       .       BAFE=0.52;BAFP=0.52;BAFS=0.503307013296771;LOGR=-0.0684284838766944
6       135997778       .       .       .       .       .       BAFE=0.45;BAFP=0.45;BAFS=0.503307013296771;LOGR=-0.0684284838766944
6       135999720       .       .       .       .       .       BAFE=0.443181818181818;BAFP=0.443181818181818;BAFS=0.503307013296771;LOGR=-0.0684284838766944
6       **1.36e+08**        .       .       .       .       .       BAFE=0.407407407407407;BAFP=0.407407407407407;BAFS=0.503307013296771;LOGR=**NA**
6       136001034       .       .       .       .       .       BAFE=0.5;BAFP=0.5;BAFS=0.503307013296771;LOGR=-0.0684284838766944
6       136001560       .       .       .       .       .       BAFE=0.636363636363636;BAFP=0.636363636363636;BAFS=0.503307013296771;LOGR=-0.0684284838766944

Thanks,

Taka

**Comment by kathryn-beal** [comment]
Hi Taka,
We have also encountered this issue and we solved it by adding the following line to the Rprofile file:
options(scipen = 999)

Regards
Kathryn

**Comment by TakaYamaguchi** [comment]
Thanks for the quick response, Kathryn!

Taka

**Comment by TakaYamaguchi** [comment]
Would you also be able to add the line in the battenberg R codes as well so that users don't have to change the default Rprofile file?

**Comment by kathryn-beal** [comment]
We do not maintain the battenberg R code. Please see the section
"Battenberg R code" on how to get in touch with the developers.
Regards
Kathryn

**Comment by TakaYamaguchi** [comment]
Thanks, I just created a ticket on their GitHub page.

Taka
