### ISSUE TITLE
libgomp: Thread creation failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by TakaYamaguchi** [cancerit/cgpBattenberg#95]
Hi,

I've been getting this error below (although I'm  using only one core) and it seems that the error is not reproducible. Has anybody reported this issue and is there a way to avoid it?

cgpBattenberg 3.3.0 with the latest dependencies

**libgomp: Thread creation failed: Resource temporarily unavailable**

Rscript -e 'library(Battenberg);  gc.correct.wgs(Tumour_LogR_file="sample_mutantLogR.tab", outfile="sample_mutantLogR_gcCorrected.tab", correlations_outfile
="sample_GCwindowCorrelations.txt", gc_content_file_prefix="/path/to/data/battenberg_wgs_gc_correction_1000g_v3/1000_
genomes_GC_corr_chr_", chrom_names=as.vector(c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","X"))) '" unexpectedly returne
d exit value 1 at /path/to/pcap/4.3.2/lib/perl5/PCAP/Threaded.pm line 256.
 at /path/to/pcap/4.3.2/lib/perl5/PCAP/Threaded.pm line 253

Thanks so much in advance.

Taka

**Comment by keiranmraine** [comment]
Please raise an issue on the repository for the [underlying R algorithm](https://github.com/Wedge-Oxford/battenberg).  Your error appears to indicate an issue in this function:

https://github.com/Wedge-Oxford/battenberg/blob/89323a28effcb7ae43964360a0f016ce280650e1/R/prepare_wgs.R#L250
