### ISSUE TITLE
Can't locate PCAP/Cli. when running in docker 

### ISSUE THREAD

**Issue by Sames-Jtudd** [cancerit/cgpBattenberg#96]
Hi, 
I've tried running Batternberg using docker. Only to receive the error  

$sudo docker run quay.io/biocontainers/perl-sanger-cgp-battenberg:1.4.1--pl526h470a237_4 battenberg.pl -h

Can't locate PCAP/Cli.pm in @INC (you may need to install the PCAP::Cli module) (@INC contains: /usr/local/bin/../lib/5.26.2/x86_64-linux-thread-multi /usr/local/bin/../lib/5.26.2 /usr/local/bin/../lib /usr/local/lib/site_perl/5.26.2/x86_64-linux-thread-multi /usr/local/lib/site_perl/5.26.2 /usr/local/lib/5.26.2/x86_64-linux-thread-multi /usr/local/lib/5.26.2 .) at /usr/local/bin/battenberg.pl line 39.
BEGIN failed--compilation aborted at /usr/local/bin/battenberg.pl line 39.

Forgive me if im wrong but I thought the whole point of docker was that the container has all the dependencies and should work off the shelf?
And given that these are effectively closed systems it would not be possible to get this to work by installing PCAP-core anyway?

thanks

**Comment by keiranmraine** [comment]
Hi,

We don't have anything to do with the bioconda packaging.  If there are issues with that you will need to raise it with them.

Unfortunately as the developers of the core R Battenberg algorithm have decided to not support new releases of the human genome (i.e. GRCh38) we no longer include cgpBattenberg in the docker image that we support.

Regards
