### ISSUE TITLE
GRCh38 breaks sprintf

### ISSUE THREAD

**Issue by ghost** [cancerit/cgpBattenberg#99]
https://github.com/cancerit/cgpBattenberg/blob/e38192d8a00e4e68a34544e6165cf7b84cc38f6b/perl/lib/Sanger/CGP/Battenberg/Implement.pm#L151

The `%d` match for contig name no longer works when contigs are named `chr%d` . We should change this to `%s`

**Comment by ardydavari** [comment]
Hi is there an ETA for a fully compatible grch38 release?

**Comment by keiranmraine** [comment]
@davidrajones (reattaching creator)

**Comment by keiranmraine** [comment]
@davidrajones I assume that this is fixed in that our internal pipeline is running with preliminary GRCh38

**Comment by davidrajones** [comment]
It is indeed. See ,aster 

https://github.com/cancerit/cgpBattenberg/blob/628a58ccfe470b287004fde89baee6e042185d47/perl/lib/Sanger/CGP/Battenberg/Implement.pm#L151
